### ISSUE TITLE
Should we use an anonymous function for CancelSubscription?

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#10]
An alternative to the current [[Cancel]] internal slot usage would be to introduce a new built-in anonymous function (CancelSubscription functions), which would have the following internal slots:

- [[AlreadyCancelled]]
- [[CancelFunction]]

It would first test [[AlreadyCancelled]] and then call [[CancelFunction]].  If there was no [[CancelFunction]] defined, then it would somehow need perform the default action (`subscriptionObserver.return`).

With the current setup we'll need to create a new bound function or anonymous function when no cancel function is provided (like the polyfill does).

**Comment by rbuckton** [comment]
If `subscribe` can take a generator, why not cancel/close the subscription when calling `next` on the generator returns an IteratorResult with `done` that is **true**?

**Comment by zenparsing** [comment]
@rbuckton it does exactly that.  This particular issue is about a spec implementation question that doesn't really have any bearing on the semantics.
