### ISSUE TITLE
Does the observable have to be an object?

### ISSUE THREAD

**Issue by evilsoft** [zenparsing/es-observable#100]
I am running into a couple cases were, if I was able to add the interface to a function, something like this from an example from an issue I posted on [most.js](https://github.com/cujojs/most/issues/283):

```javascript
function observeFunc(f) {
  const subs = []
  const done = false

  function subscribe(o) {
    if(subs.indexOf(o) === -1) {
      subs.push(o)
    }

    return {
      closed: () => done,
      unsubscribe() {
        const idx = subs.indexOf(o)
        if(idx !== -1) { subs.splice(idx, 1) }
      }
    }
  }

  function BigBoy(x) {
    const y = f(x)
    subs.forEach(s => s.next(y))
  }

  BigBoy[Symbol.observable] = () => {
    return { subscribe }
  } 

  return BigBoy
}

const x  = observeFunc(x => x)
const x$ = most.from(x)

x$.observe(console.log.bind(console, 'observed x: '))

x(2)
// observed x: 2
x(10)
// observed x: 10
```

Mind you the entire interface and proper error handling is not implemented in this brief example, but it could be fleshed out to work as defined.

I noticed you were careful to specify interface and not object in your description and I am wondering if this example were fleshed out (providing a means to end the stream and what not, as well as the other funcs), would this be acceptable under your proposal?

Having observable functions like this can remove a lot of boilerplate when building reactive views with virtual dom libs. I can combine application state updates with other view streams that can scan over a virtual dom's patching function. And as this observable function is just a function, it can be composed, lifted into an IO or Task container to control the trigger side effects.

**Comment by ljharb** [comment]
#48 may be relevant.

**Comment by zenparsing** [comment]
> I noticed you were careful to specify interface and not object in your description and I am wondering if this example were fleshed out (providing a means to end the stream and what not, as well as the other funcs), would this be acceptable under your proposal?

If you provide any object, including a function, to `Observable.from` which has a `Symbol.observable` method on it, then it will work.

```js
function f() {}
f[Symbol.observable] = function() {
  return new Observable(observer => {
    setTimeout(() => { observer.next(1); observer.complete(); }, 500);
  });
};
Observable.from(f).subscribe(x => console.log(x)); // logs "1"
```

Does that answer your question?

**Comment by evilsoft** [comment]
Yes it does thank you so much...gonna close this out to clear up some clutter. Great spec you got here!!
