### ISSUE TITLE
start(subscription:Subscription) in Observer interface

### ISSUE THREAD

**Issue by SekibOmazic** [zenparsing/es-observable#102]
This is just a simple question, not an issue.

There is a method `start(subscription:Subscription)` in the `Observer` interface (also see here: https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L83-L85) and it's not clear to me what is the purpose of this method?
Is it a kind of "trigger" for the Observer to start receiving values from the Observable?

**Comment by RangerMauve** [comment]
Pretty sure that was added in to somehow support synchronous unsubscribe. I don't really recall why, though.

**Comment by zenparsing** [comment]
@SekibOmazic It provides a way for the observer to receive a reference to the subscription, at the time that the subscription is created.  This is convenient and sometimes necessary when writing combinators which must correctly deal with the possibility that the producer sends data before the `subscribe` call completes.

An unrealistic example:

```js
let eager = new Observable(observer => {
    // Send data eagerly.  The only way for the observer
    // to unsubscribe at this point is to use "start"
    observer.next(1);
    observer.next(2);
    observer.complete();
});

eager.subscribe({
    start(subscription) {
        this._subscription = subscription;
    },
    next(value) {
        if (value > 0) {
            this._subscription.unsubscribe();
        }
    }
});
```

A more practical example:

https://github.com/zenparsing/zen-observable/blob/4cd5fbe301a5e64fce1eecef4f83258c3b718efb/src/Observable.js#L268

**Comment by SekibOmazic** [comment]
@zenparsing Thank you for clarifying this.
