### ISSUE TITLE
Show how this could underly EventTarget in the DOM

### ISSUE THREAD

**Issue by domenic** [zenparsing/es-observable#12]
I think interest in this proposal would be significantly bolstered if you can show how it can serve as a foundational layer upon which EventTarget can be built. Similarly, it's important to make sure there aren't any mismatches here, between e.g. the cancellation and bubbling semantics of EventTarget and the cancellation semantics of this.

/cc @slightlyoff

**Comment by zenparsing** [comment]
@jhusain See https://github.com/zenparsing/es-observable/blob/master/dom-event-dispatch.md
