### ISSUE TITLE
forEach returns a promise, but may also throw (if fn is not a function)

### ISSUE THREAD

**Issue by stefanpenner** [zenparsing/es-observable#16]
https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L194-L208

functions who can return a promise typically always return a promise.

**Comment by zloirock** [comment]
@stefanpenner not sure. `new Promise(null)` -> `TypeError`

**Comment by stefanpenner** [comment]
> @stefanpenner not sure. new Promise(null) -> TypeError. Looks like a similar case.

this is the single exception. For example: `Promise.all(undefined) -> RejectPromise`

**Comment by zenparsing** [comment]
@stefanpenner Agreed.

**Comment by stefanpenner** [comment]
I also feel Promise constructor scenario was a concession.
