### ISSUE TITLE
Do we need a nominal type check to confirm invariants are enforced

### ISSUE THREAD

**Issue by jhusain** [zenparsing/es-observable#18]
Will Observable.from(someObservableCreatedWithConstructor) reinforce invariants and schedule two jobs on subscription? Isn't the only way to avoid this a nominal type check?

**Comment by zenparsing** [comment]
Good point.  We could do something like Promise.resolve, where it does a brand check and a constructor match check, and return the input argument if both pass.

**Comment by jhusain** [comment]
Can we close this issue?

**Comment by zenparsing** [comment]
Added "fake" test to the polyfill.  Observable.from will get the spec treatment soon.
