### ISSUE TITLE
Observable.prototype be sealed

### ISSUE THREAD

**Issue by jhusain** [zenparsing/es-observable#19]
I think we want to avoid the hazard of the prototype being modified before we have a chance to add combinators. Don't want to break the web.

**Comment by zloirock** [comment]
Strongly opposed. If something will be added  or changed in `Observable.prototype` in future versions, it will break patching `Observable` polyfills.

**Comment by benjamingr** [comment]
+1 @zloirock

**Comment by jhusain** [comment]
Point well taken. Closing issue.
