### ISSUE TITLE
Motivate subscribe vs forEach

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#20]
Hey, can we get an example motivating why both subscribe and forEach are needed?

**Comment by jhusain** [comment]
Async/Await Observation.

```JavaScript
async function getPriceHigh(stock) {
    let delta,
        high = Number.MIN_VALUE;

    let socket = new WebSocket(“/dailyPrices/" + stock);
    await Observable.from(socket).forEach(price => {
    	  if (price > high) {
	      high = price;
	  }
    });

    return high;
}
```

**Comment by zenparsing** [comment]
An interesting question on the table is if we could merge `subscribe` and `forEach` by making the subscription object a promise (or thenable).

So in the example, you could just replace the `forEach` with `subscribe` and it would work fine:

```js
await Observable.from(socket).subscribe(price => {
  if (price > high) {
    high = price;
  }
});
```

It would be a nice simplification, all other things being equal.

**Comment by benjamingr** [comment]
Yes, this definitely seems like a good idea to merge the two - there is nothing preventing subscribe from being a `then`able/promise.

**Comment by jhusain** [comment]
Not sure why this is attractive. Promise essentially duplicates semantics of return() and throw() callbacks passed to subscribe. Would also like to understand performance implications.

**Comment by jhusain** [comment]
what a happens if I do this:

try {
await obs.subscribe({ throw(e) { /* error handling */ }, return(v) { /* error handling */ } }) 
}
catch(e) {
// other error handling
}

Gives the developer of the opportunity to duplicate error handling logic two places. furthermore the Observer callbacks may or may not  be executed synchronously, whereas the promise error will only be  executed asynchronously. This seems like a big foot gun to me.

**Comment by jhusain** [comment]
Big mistake to build observable with promises. There is too much semantic overlap, coupled with impedance mismatch. adapting between them is unambiguous.

**Comment by domenic** [comment]
> what a happens if I do this:

Yes, agreed. It seems this proposal could be greatly simplified by removing subscribe and [Symbol.observe] in favor of forEach---at least, assuming we get cancelable promises. With that assumption there's no loss in power and a great increase in interoperability and compositionality.

**Comment by zenparsing** [comment]
I agree as well and withdraw the suggestion : )

**Comment by jhusain** [comment]
Withdrawing Symbol.observe and subscribe on the assumption that Cancellable
Promises would couple these two proposals which seems risky. However having
forEach around means that we could simplify the proposal at a later stage
if Cancellable Promises gains traction.

**Comment by domenic** [comment]
Yeah, agreed. I like the plan of keeping both for now in the hope of removing one if we get cancellable promises shipping soon. Nice.

I still think having both [Symbol.observe] and subscribe is a bit redundant but I haven't dug into it much and we can move that to another bug.

**Comment by zenparsing** [comment]
Any objections to closing this one?

**Comment by benjamingr** [comment]
Resolution sounds good to me :+1:

**Comment by benjamingr** [comment]
Resolution sounds good to me :+1:

**Comment by benjamingr** [comment]
Re-reading this, why would `subscribe` returning a `then`able mean we'd have to have cancellable promises in order for observers to be cancellable? 

Can't subscribe return a `then`able/Promise which is also a subscription and we get to have the best of both worlds?

**Comment by blesh** [comment]
> why would subscribe returning a thenable mean we'd have to have cancellable promises in order for observers to be cancellable?

@benjamingr because `subscribe` should return a mechanism for notifying the producer to stop pushing values (unsubscription/cancellation)

**Comment by benjamingr** [comment]
Yes, but why not both? Why can't it have `then` and `unsubscribe`

**Comment by blesh** [comment]
Because at that point someone will argue that it should be a cancelable promise, which marries the two proposals. I don't think cancelable promises are a great idea, personally.

**Comment by benjamingr** [comment]
> Because at that point someone will argue that it should be a cancelable promise, which marries the two proposals. I don't think cancelable promises are a great idea, personally.

I agree (with not marrying the proposals). What I'm asking is - why can't we return a promise which is a subscription that can be disposed? 

That way if _in the future_ cancellable promises make it we'll also make the returned promise cancellable to benefit from facilities but we get a subscription with a `then` and an `unsubscribe` which means we can `dispose` it and `await` it. Wouldn't that be worth it?

**Comment by blesh** [comment]
@benjamingr at this point I honestly think the subscribe function should return a generator type that also has the `dispose` method that is sorely missing from Generator. If there were a proposal to marry it to, it would be the proposal of putting a `dispose` method on Generator that only called the generator's finally block. cc/@jhusain

**Comment by benjamingr** [comment]
The generator subscription proposal is starting to grow on me.

Since it is now a sequence, I wonder if `await*` can be used instead of `await`, this also has the nice property of showing that it's in fact a sequence that's being awaited.

It would require `next` on the returned subscription, that would have to return promises _somehow_ in order to work with `await*` though. Do you think a new thread should be opened?
