### ISSUE TITLE
Design assuming cancellable promises

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#21]
This page is a mental playground assuming we get cancellable promises in JavaScript. It is not suggested for the API of this proposal - it's only here to explore some semantics _in that case_. The content here is _not_ a suggestion for the API.

---------------------

So, assuming they eventually land. I have some things I'd like to discuss.

 - I'm not sure that `.forEach` is a good name for something that returns a `then`able, especially if we want to allow it to run without arguments. Dart uses `forEach` for something similar though. They also have `.listen` and their subscriptions have `.asFuture`  values.
 - Cancellation should hook to disposing the stream.
 - Generally, the mapping between observables and promises should primarily focus on `async/await` semantics.

Optimally, assuming we've already had cancellable promises with the proposed semantics, as @jhusain pointed out we won't want to duplicate the `done` handler but we _do_ need a way to handle errors in the stream on a case by case basis. 

**So I think `.forEach` (assuming the name sticks) should allow handling errors** - while the converted-to promise can signal being done or an error on the stream as a whole, with current `.forEach` there is no way to handle a _single_ error in a stream and recover from it.

**It should allow running it without passing a handler in** - this way you can hook on it and `await` it easily.

**The promise should be for the last element of the stream**  - this can be useful for single valued streams - while it's not the most correct approach theoretically it's the most pragmatic. 

Cancellation translation itself should be pretty straightforward.

**Comment by domenic** [comment]
> I'm not sure that .forEach is a good name for something that returns a thenable, especially if we want to allow it to run without arguments.

Hmm. Now that you mention it I am a bit confused. The forEach name is good in analogy with e.g. map, I thought: in a sync world, you have

```
map: Iterable -> Iterable
forEach: Iterable -> void
```

In an observable world you would then expect

```
map: Observable -> Observable
forEach: Observable -> Promise<void>
```

But this is not actually how things work, since it's a promise for the observable return value, which is not always undefined. Maybe it is more accurate to add types like `Observable<SequenceType, ReturnType>` (abbreviated `Observable<S, R>`). In which case it becomes, I believe

```
map: Observable<S1, R> -> Observable<S2, R>
forEach: Observable<S, R> -> Promise<R>
```

I guess that is OK, but it kind of highlights that the return values feel a bit tacked on, in that they aren't manipulable by any of the combinators.

> we do need a way to handle errors in the stream on a case by case basis. 

I either disagree with this or don't know what you mean by this. A sequence can yield values and then eventually return or throw. But once it does one of those two things, the sequence is over forever. There's no recovery. That's true for sync generators (and built-in sync iterators) and seems reasonable for both async observables and async iterators.

> The promise should be for the last element of the stream - this can be useful for single valued streams - while it's not the most correct approach theoretically it's the most pragmatic. 

This doesn't make sense given that observables already have return values built-in and/or tacked on. Single-valued situations are handled in .NET fairly well IMO with First/FirstOrDefault/Single or whatever they were, which would be promise-returning in this case.

**Comment by benjamingr** [comment]
>  A sequence can yield values and then eventually return or throw. But once it does one of those two things, the sequence is over forever. 

I think this misses a lot of potential, let's say I'm making web requests in sequence and one failed - I'd like to be able to recover for that particular request and not touch anything else in the sequence. That said I'm not sure where this particular proposal stands on the subject.

> I guess that is OK, but it kind of highlights that the return values feel a bit tacked on, in that they aren't manipulable by any of the combinators.
> ...
> This doesn't make sense given that observables already have return values built-in and/or tacked on. Single-valued situations are handled in .NET fairly well IMO with First/FirstOrDefault/Single or whatever they were, which would be promise-returning in this case.

See [this issue on Rx](https://github.com/Reactive-Extensions/RxJS/issues/538) which I argue the opposite (your) position. In practice people using observables like having the last value. So while in theory I agree that it's not the most correct API - in practice it's what people enjoy using. I think an analogy would be returning the last value in a generator behaving differently from previous values (with return and not yield).

**Comment by domenic** [comment]
> That said I'm not sure where this particular proposal stands on the subject.

It's fairly clear that calling .throw() or .return() sets the observer to [[Done]] so that all future calls are default, and doing so also cancels the subscription.

**Comment by domenic** [comment]
> See this issue on Rx which I argue the opposite (your) position.

Nobody in that issue mentions Rx observables having the auxiliary return value channel... do they?

**Comment by jhusain** [comment]
Agree that forEach should produce a Promise<void>. The goal is to approximate a for loop as closely as possible. Later on if we introduce a for...on I would like an easy refactoring path.

JH

**Comment by zenparsing** [comment]
@benjamingr 

> That said I'm not sure where this particular proposal stands on the subject.

The sequence terminates with either an exception or a return value.  SubscriptionObserver doesn't allow any further notifications to the wrapped observer.

The rationale here is that observed sequences should obey the same rules as iterated sequences.  Although iterators can do whatever they want, a well-behaved iterator (as implemented by generator functions) will have the following properties (among others):

- If the iterator throws, then subsequent calls to next will return `{ done: true }`.
- If the iterator returns `{ done: true }`, then subsequent calls to next will return `{ done: true }`.

The idea is to ensure the same sequence "laws" for observed sequences.

**Comment by benjamingr** [comment]
Roger, thanks for clarifying. 

@jhusain as the heaviest observable user here - you're OK with not being able to recover from mid-stream errors? Wouldn't that severely limit observables in the future?

**Comment by jhusain** [comment]
Yes. It's important to recall that it's possible to build streams that send multiple errors as a protocol on top of streams that don't. Also Duality between Iterable and Observable is paramount to preserve because it means we are much less likely to make a design mistake.

JH

**Comment by benjamingr** [comment]
Fair enough.
