### ISSUE TITLE
Why is `.subscribe`'s subscriber a generator and not an async function?

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#22]
Wouldn't it make more sense if an async function was passed into `Observable.prototype.subscribe(observer)`?

Current:

```js
function consumer() {
    let generator = function*() {
        while (true) {
            console.log("Recieved key command: " + (yield));
        }
    }();

    // "Prime" the generator so that it can receive the first value from the producer
    generator.next();
    return generator;
}

commandKeys(inputElement).subscribe(consumer());
```

Asking about:

```js
async function consumer() {
        while (true) {
            console.log("Recieved key command: " + (await));
        }
}
commandKeys(inputElement).subscribe(consumer);
```

**Comment by domenic** [comment]
`await` with no argument doesn't even work. What are you awaiting?

**Comment by benjamingr** [comment]
Right, I think we can generally ignore everything I post before I properly wake up. It would be nice to be able to do this but it's just not the semantics we have.

**Comment by DylanPiercey** [comment]
I know this is closed but couldn't we use Async Generators for this (at least it's so in babel)

```javascript
async function* consumer() {
        while (true) {
            console.log("Recieved key command: " + (yield));
            doStuff(await something())
        }
}
commandKeys(inputElement).subscribe(consumer);
```

**Comment by blesh** [comment]
@DylanPiercey this dovetails with this stage 1 ECMAScript proposal: https://github.com/jhusain/asyncgenerator

**Comment by zenparsing** [comment]
@DylanPiercey Thanks - I want to respond to your question but need to do some thinking first.  Ping me if I don't get back to it within a day or two.  : )
