### ISSUE TITLE
Nits regarding internal slots

### ISSUE THREAD

**Issue by domenic** [zenparsing/es-observable#23]
You use O.[[Done]] in a few places, but dot notation is only for record fields, not object internal slots. (We may move toward O@[[Done]] in the future, so I will use that for brevity, but probably for the spec draft you should stick to "the [[Done]] internal slot of O".)

When you set O@[[Done]] to true, I believe you can reset O@[[Subscription]] and O@[[Observer]] to undefined to release references to them. Technically implementations could do this without you needing to specify, but I think it's clearer to make the strong references more explicit, and when I was researching this for promises I found a few other places in the spec that also clear out references.

**Comment by zenparsing** [comment]
Thanks for the review!

It looks like I can get rid of [[Done]] altogether if I drop the reference to [[Observer]], and just check [[Observer]] === `undefined` instead of checking [[Done]].  Do you think that would be a good thing for the spec?

**Comment by domenic** [comment]
Yeah I was thinking something like that might work but I hadn't read through all the other places [[Observer]] was used so I wasn't sure. Agreed that it works nicely.
