### ISSUE TITLE
Observable.from semantics

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#26]
The idea of `Observable.from` is that it takes something that is "observable" and it returns an Observable proper.  If the input is actually an Observable, then it simply returns the input.

Currently, it does this by looking for a method named `Symbol.observer`, which directly implements the core subscription protocol.  If you want to make an abstraction "observable" (and compatible with `Observable.from`) then you would provide a `Symbol.observer` function:

```js
Promise.prototype[Symbol.observer] = function(sink) {
    this.then(value => {
        sink.next(value);
        sink.return();
    }, error => {
        sink.throw(error);
    });
    return { unsubscribe() { sink.return() } };
};
```

Notice how the method above isn't really directly usable:  we can't just provide any old observer to it.  It expects an observer which (at the very least) has "next", "throw", and "return" implemented.  Notice also how we have to roll our own subscription object which may or may not uphold any invariants.

Another option would be to create a level of indirection and introduce a new `Symbol.observable` which would give you back an observable.  It would work much like `Symbol.iterator`.

The example above would become:

```js
Promise.prototype[Symbol.observable] = function() {
    return new Observable(sink => {
        this.then(value => {
            sink.next(value);
            sink.return();
        }, error => {
            sink.throw(error);
        });
    });
};
```

This seems like a much easier way for programmers to make their abstractions observable, rather than requiring them to implement all of the subscription semantics from scratch.

Of course, one could always choose to implement the raw interface like this:

```js
class C {
    [Symbol.observable]() {
        return {
            [Symbol.observer](sink) { /*...*/ }
        };
    }
}
```

What do you think?

**Comment by zloirock** [comment]
BTW [`this.constructor`](https://github.com/zenparsing/es-observable/blob/28a8316b10bafb051da616de16909ea2269b8bb4/src/Observable.js#L292)? Looks like bug.

**Comment by zenparsing** [comment]
@zloirock indeed - thanks!

(And probably still not quite right given that I haven't spec it yet.)
