### ISSUE TITLE
chainability of custom operators

### ISSUE THREAD

**Issue by danylaporte** [zenparsing/es-observable#30]
How will it be possible to chain custom operators?

```js
var observable = listen('button', 'click')
   .pipe(myCustomOperator()) // should we have a pipe operator?
   .filter();
```

Is it possible to have a pipe operator instead of extending the prototype?

**Comment by benjamingr** [comment]
Yes, we have a `::` (bind) operator proposal that enables this - you might
want to check that out.

**Comment by danylaporte** [comment]
That would do the job. Thanks!
