### ISSUE TITLE
Pausing / resuming a subscription

### ISSUE THREAD

**Issue by danylaporte** [zenparsing/es-observable#31]
This would be very interesting to have support for pausing and resuming subscription. 

- backpressure
- max concurrency
- priorization

**Comment by benjamingr** [comment]
Interesting, but as @jhusain has pointed out this is something that is composed on top of the current approach at a later point (Jafar, correct me if I'm wrong please) and I think we're aiming for a minimal set for this proposal (correct me if I'm wrong Kevin).

**Comment by domenic** [comment]
Pausing/resuming is a *very* bad and error-prone way to do backpressure, as has been discovered in various streaming APIs.

**Comment by jhusain** [comment]
@benjamingr we are definitely going for a minimal set of semantics for this proposal. Back pressure could be supported by an asynchronous iterator, or an asynchronous observable proposal in the future.

**Comment by benjamingr** [comment]
Yes, I think this can be closed for out of scope at this point and figured out later.

**Comment by danylaporte** [comment]
Sure, thanks.
