### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#36]
It would be nice to have a chat channel (IRC, slack or gitter) to toss up non-formal ideas about this spec in. 

Currently I talk to Erik in emails, Domenic in IRC, spion in IRC and Facebook and Jafar Ben and Kevin only in GH.

It would be nice if interested parties could discuss ideas (without opening issues first) somewhere. I don't really mind where as long as it's public.

**Comment by boopathi** [comment]
:+1: That'd be good. I personally have some doubts and suggestions, but silent so as not to pollute the discussions. Chat would be nice to clear some doubts and less noise in this repo.

**Comment by zenparsing** [comment]
Feel free to set something up if you have time or the inclination to do so.  I probably won't be able to participate much though.
