### ISSUE TITLE
Remove generators as subscribers.

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#39]
Per the consensus on https://github.com/zenparsing/es-observable/issues/35 .I think the spec should be updated to reflect that agreement.

(Assuming we have synchronous unsubscription regardless of whether or not subscription is sync or async)

**Comment by zenparsing** [comment]
It should, but I want to see where we go with subscription semantics before going much further.  The polyfill has been updated in the "callback-style" branch, but I'm still experimenting there.

**Comment by benjamingr** [comment]
> The polyfill has been updated in the "callback-style" branch, but I'm still experimenting there.

Excellent! I'll play with it. Keeping the issue open for updates until the master branch gets updated.

**Comment by zenparsing** [comment]
Note that in that branch subscription is currently sync, but `Observable.of` (for example) delivers it's values in a future job.  Attempting to `next` within the subscriber function currently throws;  I'm not actually proposing that, just experimenting.

**Comment by blesh** [comment]
> Observable.of (for example) delivers it's values in a future job. 

@zenparsing interesting. Why?

**Comment by zenparsing** [comment]
I was experimenting with the idea that observables shouldn't start dispatching until after the `subscribe` call has completed.  Basically, while the subscriber function is executing the subscription is in an "initializing" state and is unable to receive data yet.  That addresses the zalgo problem, while letting EventTarget/Subject stuff work as expected.

**Comment by blesh** [comment]
@zenparsing ah, so subscription and observation are synchronous, but cannot occur simultaneously?

**Comment by zenparsing** [comment]
@blesh Yeah - that was the idea.  In a way it makes sense; it was kind of weird how we could "complete" the stream within the subscriber, but we couldn't run the dispose function synchronously because it hadn't been returned yet.

On the other hand, it's a little weird handing a set of callbacks to the subscriber that aren't able to be called yet.

**Comment by blesh** [comment]
That maps to what EventTarget does. You can't really subscribe to a event *and* dispatch it while doing so... However I worry that we're not thinking about how this might effect some scenarios. A simple `Observable.range(0, Number.MAX_VALUE)` comes to mind. Observable.range would then queue all of those integers to be emitted synchronously after subscribe completes. Presumably, whatever you're doing after the `range` is probably something that is only going to "takeUntil" some point; but you'll already have queue'ed the whole shebang.

**Comment by benjamingr** [comment]
@zenparsing how would observable an multicast look like (implemented from the userland)?

@blesh we can defer emitting all the numbers, this is O(1)

**Comment by zenparsing** [comment]
@blesh 

In this scenario, you'd write `range` something like:

```js
Observable.range = function(from, to) {

    return new Observable((next, error, complete) => {
    
        let stop = false;
        
        enqueueJob(_=> {
            for (let i = from; i <= to && !stop; ++i)
                next(i);
            complete();
        });
        
        return _=> stop = true;
    });
};
```

**Comment by zenparsing** [comment]
@benjamingr 

Not sure if this is what you were asking, but you could implement an (overly simple) multicast combinator like this:

```js
function multicast(observable) {

    let listeners = new Map;
    
    let subscription = observable.subscribe(
    
        value => {
            for (next of Array.from(listeners.keys()))
                next(value);
        },
        
        error => {
            for (callbacks of Array.from(listeners.values()))
                callbacks[0](error);
        },
        
        complete => {
            for (callbacks of Array.from(listeners.values()))
                callbacks[1]();
        }
    );

    return new Observable((next, error, complete) => {
        listeners.set(next, [error, complete]);
        return _=> listeners.delete(next);
    });
}
```

For real-world usage, you'd probably want to make it so that errors from different subscribers don't interfere with each other.  You also might want to only start the source subscription on the first listener subscribe, or unsubscribe when the listener count drops to zero.

**Comment by benjamingr** [comment]
I think discussion here is superceded by https://github.com/zenparsing/es-observable/issues/43
