### ISSUE TITLE
Interop: Observable.resolve?

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#40]
I think `[Symbol.observer]` is a good interop point for *reading* from an "Observable-esque" type, but we're lacking for interop is a method akin to Promise's resolve.

### Use Case

I'm a library author and I've been given an arbitrary object I want to ensure is an Observable for my library's use. It's likely async or a collection of some type, but it could be a simple value type.

### Thoughts 

The basic principal is that it would be a method that examined the input for a `[Symbol.observer]`, if it found it, it would subscribe to that and return a new Observable, next it would look for `[Symbol.iterator]`, otherwise it would create an observable from whatever value is passed. I'm really not sure how this would work, just wanted to start discussion around it:

### Different scenarios:

1. Observable.resolve(observablesque); -> subscribe to `observablesque` with Symbol.observer and output Observable.
2. Observable.resolve(valueType); -> An observable of one item
3. Observable.resolve(iterable); -> An observable of N items from the iterable
4. Observable.resolve(object); -> An observable of one item
5. Observable.resolve(promise); -> An observable of one item

### Pain points

- I can see Arrays and generators mapping to Observables just fine, but Strings are iterable, and I think most of the time people will want those to be mapped into an observable of item.
- For promises and single values, do we just make an observable that nexts out one value? Should it complete/return with that one value also?
- The name `resolve` doesn't make much sense to me... is there a better name for it?

**Comment by zenparsing** [comment]
Thanks for raising this issue.  Please check out `Observable.from` in the "callback-style" branch.  It does something very similar to what you're asking for.  In fact, I think between `Observable.of` and `Observable.from` it should cover the bases.

The big design change I made is that I introduced `Symbol.observable`.  This works just like `Symbol.iterator`:  for some arbitrary "observable" type, it returns an observable object.  Like iterators, observables have a `Symbol.observable` method which just returns `this`.

We could add `Symbol.observable` to Promise.prototype as well, which would make them convertible with `Observable.from`.

**Comment by zenparsing** [comment]
It looks like the scenarios can be mapped to `from`/`of` like this: 

1. "observablesque" => Observable.from.
1. valueType => Observable.of
1. iterable => Observable.from
1. object => Observable.of
1. promise => Observable.from (potentially)

The only issue is that you have to know whether to call `from` or `of` in advance.  That makes sense to me though, because the two operations are very different from a type point of view:

```
Observable.from(Observable<T>) : Observable<T>
Observable.from(Iterable<T>) : Observable<T>

Observable.of(T) : Observable<T>
Observable.of(T, U) : Observable<any>
Observable.of(T, U, V) : Observable<any>
...
```

I think a more heuristic casting function would be useful, but maybe not appropriate for the core API?

> I can see Arrays and generators mapping to Observables just fine, but Strings are iterable, and I think most of the time people will want those to be mapped into an observable of item.

Again, I don't think I'd feel comfortable adding such a heuristic.  The `from`/`of` distinction seems good to me and allows users to express their intent explicitly.

> For promises and single values, do we just make an observable that nexts out one value? Should it complete/return with that one value also?

That's a good question.  `Observable.of` takes a variable number of arguments, so it makes sense to `next` each one and then complete with `void` (like all other iterable sequences).

For promises, my personal opinion is that it should `next` the fulfillment value and then complete with `void`.  It's just so much easier to consume that way with the callback style:

```js
Observable.from(promise).subscribe(
    val => console.log(`Resolved with ${ val }`), 
    err => console.log(`Boo, rejection! ${ err }`));
```

And it has a nice symmetry with `then`:

```js
promise.then(
    val => console.log(`Resolved with ${ val }`), 
    err => console.log(`Boo, rejection! ${ err }`));
```

**Comment by blesh** [comment]
I think there should just be one method that you can use to convert *anything* to an observable, personally. Perhaps that's `from`. `of` seems more specialized.

### On Promise conversion

Are we still going with the `return`\`completed` path returning a value? If so, it seems like Promises would map 1:1 with something like just returning the resolved value. However, that makes composing over the Observable painful. There are really three options:

1)
```
new Observable(o => {
  promise.then(x => {
     o.next(x);
     o.return();
  }, err => o.error(err));
});
```

2)
```
new Observable(o => {
  promise.then(x => {
     o.return(x);
  }, err => o.error(err));
});
```

3)
```
new Observable(o => {
  promise.then(x => {
     o.next(x);
     o.return(x);
  }, err => o.error(err));
});
```

I think 1 or 2 are acceptable. 3 seems weird. 1 makes it the easiest to compose. 2 gives more purpose to the whole "return having a value" thing, and means every Observable that has a return value could be treated somewhat like a promise.

My gut tells me the right thing to do is go with 1, and then have a specialized "ScalarObservable" that matches the signature of Observable, but only ever emits one value. That, of course doesn't need to be part of this proposal, but as a library implementor, I might just add a boolean check for an `isScalar` or the like so I can optimize code paths.

**Comment by zenparsing** [comment]
> I think there should just be one method that you can use to convert anything to an observable, personally. 

I'm a little worried that if you make such an all-accepting function, it will be a breaking change to make some type T observable-ish if it was previously not observable-ish.  It would cause the behavior to go from:

```
from(T) : Observable<T>
```

to:

```
from(observablesque<T>) : Observable<T>
```

> My gut tells me the right thing to do is go with 1

Mine too, but maybe @jhusain has a different opinion?

**Comment by benjamingr** [comment]
Definitely in favor of 1 here. If observables don't have a return value it's as simple as the fact:

     a; // value
     [a]; // array containing one value.

__That said__, I think it's important to keep consistency with async iterators. So observables should probably behave consistently to those.

**Comment by jhusain** [comment]
The breaking change hazard is real unfortunately. Under the circumstances, we should probably go with option one.

**Comment by benjamingr** [comment]
@domenic can you clarify what async iterators do here so observables can align?

**Comment by domenic** [comment]
What am I clarifying? @zenparsing is the expert on async iterators anyway as it's his proposal. Your code looks a bit suspicious in that it does `yield 1` instead of `return 1` but I don't have any context.

**Comment by benjamingr** [comment]
@domenic ok then, apologies for the ping don't waste time on it - @zenparsing will clarify it :)

**Comment by blesh** [comment]
I think Observable.from solves this adequately for now. Closing.
