### ISSUE TITLE
Problems with Observable without Observer: multicasting/Subjects

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#42]
I realize Subject is not a party of this spec, but it is a part of the Observable ecosystem. 

If there are no Observers, what is a Subject?  How can a Subject subscribe to an Observable? I suppose it can be done with closures, but that sort of breaks Subject.

**Comment by benjamingr** [comment]
How do you feel about https://github.com/zenparsing/es-observable/issues/41#issuecomment-120954963 ?

**Comment by zenparsing** [comment]
Closing since we have Observer again.
