### ISSUE TITLE
Unifying `forEach` and `subscribe` return value - Subscriptions

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#44]
I propose the following changes to subscription and the API.

Both `forEach` and `subscribe` return a `Subscription`.

 - **A subscription is a `then`able** (a promise, basically), this means we `await` subscribe, or `forEach`, it runs when the observable is done. The returned promise resolves with either the completion or the error of the sequence. The `.then` method is a getter and _it creates the underlying promise only when it is accessed_ so there is no overhead for `then` unless we use it. It is a promise for `undefined` so no value needs to be cached and there is no mismatch with observable semantics
 - **A subscription has a `dispose` method** which is _unrelated to promise cancellation. If we choose in the future to also support the cancellable promises API that's nice, but we don't want to tie the two proposals. 

In addition, I'm open to any form of sync/async disposal semantics you guys need. This is mainly about unifying the return value of `subscribe` and forEach` without conflating the proposal with cancellable promises. I've also found myself wanting (needing) to `await` the result of subscribe in combinators (merge two observables in order for example).

Let me know what you think.

**Comment by zenparsing** [comment]
@benjamingr The problem that we mentioned in the other thread is that we don't want to mix error handling mechanisms.  For instance:

```js
let s = obs.subscribe({
  next(x) {},
  error(x) {},
});
s.catch(x => {});
```

This would confuse error handling.

I would like to introduce a counter-proposal:

- We eliminate `Symbol.observer` (synchronous subscription) and make `subscribe` synchronous, like Rx.  The "subscribe" method has no zalgo-protection.
- `forEach` performs subscription asynchronously and has zalgo-protection and returns a normal promise.  The error or return values are channelled through the promise.
- The argument to `forEach` accepts a value and a subscription object, which can be used to short-circuit.

```js
// No zalgo-protection with subscribe
let subscription = observable.subscribe({ next, error, complete });

// forEach subscribes in a job, and flows errors and completion through the promise
observable.forEach((value, subscription) => {
  whatever;
}).then(
  returnValue => {}, 
  errorValue => {}
);
```

**Comment by benjamingr** [comment]
@zenparsing 

> @benjamingr The problem that we mentioned in the other thread is that we don't want to mix error handling mechanisms. For instance:

Why? Can't we just let `catch` for the observer run first and if no handler is attached or it threw let the promise handle it. In this proposal, the promise has no meaningful return value anyway so "value recovery" isn't a problem here.

**Comment by benjamingr** [comment]
That is: the `catch` on the promise only signifies that the observer terminated abruptly __and that it didn't handle it in a `catch`__, this has the benefit of aligning with `async/await` and throwing in the surrounding scope as well as benefiting from existing unhandled promise rejection tracking mechanisms

**Comment by blesh** [comment]
I like @zenparsing's proposal better, and I agree, I think it's best to keep the subscription type simple. If we go to the extreme the other way, you could just about make a Subject out of the Subscription.

**Comment by benjamingr** [comment]
I see a ton of benefit to being able to await `subscribe` and not so many downsides. The channeling of error through the promise in `forEach` happens either way (since no `error`) - remember, making it a `then`able is free in this case - no promise needs to be allocated per subscription unless you use it. 

In both proposals you can make a subject out of the subscriber that's not really an issue with either.

I'm also +1 on `forEach` having zalgo protection but I'm still interested in seeing how `subscribe` can be made safer (that's another issue though). I'm also +1 on an additional `subscription` argument in every `next` callback, be it `forEach` or `subscribe` I really like that idea.

**Comment by blesh** [comment]
I think it's semantically weird:

```js
myObservable.subscribe(blah).then(doSomething);
```

Reads like:  "Once you're subscribed, then do something".  `subscribe` is usually the end of the chain.

**Comment by benjamingr** [comment]
Right, to be fair in 99.9% of cases most people would be using it as:

```js
    await myObservable.subscribe({ next(v){
          doSomethingWith(v);
    /*...*/});
```

It's just useful to `await` `subscribe` in my opinion and I expect I'll use it in my code if it's available. It bothers me that if I `forEach` I can't access the callbacks using the observer interface - making any code that utilizes it (like specific instances of observer I create) impossible to use in this scenario. This is more painful if I implement a `Subject` in my code and I want to run the subject and await the subscription. 

Given a `then` can be a getter and is free and it's useful, I'm not sure why we wouldn't want to have it for `async/await` support. It also means we can pass subscriptions to code using promises and it'll wait for the sequence to finish which is also useful.

**Comment by zenparsing** [comment]
@benjamingr Mixing async primatives at a basic level (i.e. `subscribe`) is going to be problematic.  It can be done, but the clean way to do things is to keep them separated.

I am interested in a `forEach`-style alternate subscription function which only accepts a single callback and returns a promise for the return value or error.  However, such a subscription function would essentially be an async task and until we have a story for cancellation of async tasks...

As I note at the end of the README, `forEach` is deferred for now.

To be honest, I'm actually more interested in allowing observables to be async-iterable:

```js
async function af(observable) {
    for async (let x of observable) {
        // process observed values, throw if error, etc.
    }
}
```
