### ISSUE TITLE
Async subscriber functions

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#45]
For some time, I've been wanting to somehow provide an ergonomic way to use async functions as subscriber functions:

```js
let obs = new Observable(async observer => {
    observer.next("Hello");
    await new Promise(resolve => setTimeout(resolve, 2000));
    observer.next("World");
    await new Promise(resolve => setTimeout(resolve, 2000));
    return "Sweet!";
});

obs.forEach(::console.log).then(
    x => console.log("All done: " + x),
    err => console.log("Error: " + err));
```

Outputs:

```
Hello
World
All done: Sweet!
```
Proposal:

If the subscriber function returns a promise, then listen for that promise's fulfillment value and call `observer.error` or `observer.complete` accordingly.

https://github.com/zenparsing/es-observable/blob/403c3084b9d28dec23646e6a37f36d1c0c74a84e/src/Observable.js#L201-L208

Thoughts?

**Comment by domenic** [comment]
> If the subscriber function returns a promise

General promise use frowns on this kind of type-testing. Rather, you should instead cast the expected-to-be-promise to a promise using Promise.resolve. That doesn't work in this case.

So instead I think a specialized factory or something similar would be more sensible.

**Comment by blesh** [comment]
How would someone return the disposal function from this?  What's a real world use case where this would be desirable?

**Comment by zenparsing** [comment]
@domenic Yeah that sounds better.

@blesh I was thinking that the async function could check the subscription status via `observer.isUnsubscribed` or somesuch, and perform cleanup in response.

**Comment by blesh** [comment]
@zenparsing will observer have an `isUnsubscribed`?
