### ISSUE TITLE
Interop and Symbols

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#46]
In speaking with @stefanpenner a few weeks ago, he was saying that Ember might like to use `Symbol.observer` to test for the "Observable-iness" of a value and subscribe to it when binding templates (I think that was what we discussed).

Anyhow, it occurs to me that Symbols are useful for interoperability because they can be tested for and called cleanly.

`Symbol.observer` was taken away, AFAIK. What are the planned interop points in both directions? I know `from` and `of` have been mentioned in prior threads. What about to read from? Also, how do you feel about using symbols?

**Comment by zenparsing** [comment]
@blesh My suggestion (haven't received much feedback yet though) would be to mimic iterables here.  In other words, we introduce a `Symbol.observable`.  If something is "observable", then it returns an observable object when that method is called.  Observables just return themselves from that method.

`Observable.from` would use that method to convert some "observable" thing to an Observable.

https://github.com/zenparsing/es-observable/blob/4c97fd72f830348a559d024fabe654dcd334cd00/src/Observable.js#L245

Thoughts?

**Comment by RangerMauve** [comment]
Is defining properties on Symbol the way APIs are planning to go in the future? I would almost expect things like Observable to have their symbol be defined under the Observable object to keep is separate.

**Comment by blesh** [comment]
> Is defining properties on Symbol the way APIs are planning to go in the future? 

@RangerMauve it seems like this is following "prior art" of things like `Symbol.toStringTag`, `Symbol.iterator` etc.

>  My suggestion (haven't received much feedback yet though) would be to mimic iterables here. In other words, we introduce a Symbol.observable

Isn't Iterable's way a `Symbol.iterator` that returns an `iterator` though? Wouldn't the opposite of that be the original `Symbol.observer` proposal that accepts an Observer? I realize it's the *same* as subscribe, but I think there's utility in marking it with a Symbol, because that atomic thing becomes "symbolic" for "Hey I can be read from like an observable" ... just like `Symbol.iterator` says "Hey, I can be iterated over" on String or Array, etc.

At the very least, having a symbol `Symbol.observer` on Observable enables someone to test to see if it has a `from` method on it too, perhaps? I think the use case for that as an interop "thing" is limited, but perhaps in situations where a library or framework wants you to specify what sort of Observable type you'd like returned (Rx, Bacon, Most, etc), it can test for "observable-iness" and use `from`?

**Comment by blesh** [comment]
@RangerMauve ... FWIW: I think that you're right if we were talking about a *library* API. But for core JavaScript API, I think `Symbol` is the place to put symbols, just by prior convention.

**Comment by zenparsing** [comment]
@blesh 

`Symbol.observable` allows you to mark a thing as observable without having to implement subscribe (or its Symbol-equivalent) on it.

For example, I'm not really going to want to do this:

```js
class SomeAbstraction {
    [Symbol.observer](observer) {
        return new Observable(observer => {
            // ...
        }).subscribe(observer); // Notice I need to immediately invoke subscribe
    }
}
```

I'd much rather write:

```js
class SomeAbstraction {
    [Symbol.observable]() {
        return new Observable(observer => {
            // ...
        });
    }
}
```

`Symbol.observable` gives a nice layer of indirection that lets me separate an abstraction from the observable which can be used to observe it.

**Comment by blesh** [comment]
Sounds good to me. I'm curious what a framework author that might consume something like this might think. @vsavkin @jeffbcross @stefanpenner

**Comment by stefanpenner** [comment]
cc @mmun

**Comment by blesh** [comment]
cc @igorminar

**Comment by IgorMinar** [comment]
+1 for `Symbol.observable`

**Comment by blesh** [comment]
I'm good with `Symbol.observable` and `from` / `of` for interop I think. Closing this issue.
