### ISSUE TITLE
 Add Observable.from, Symbol.observer key

### ISSUE THREAD

**Issue by jhusain** [zenparsing/es-observable#5]
We want to support both synchronous and asynchronous subscription, but only synchronous notification. To guard against the dangers of synchronous subscription for casual users, we would like to introduce an easily-discoverable method ("subscribe") which automatically schedules on the micro task scheduler. However to enable those writing combinator libraries to do composition efficiently,  we would like to add another method:

Symbol.observer

This method is not expected to Introduce any asynchrony. It is a new contract we are proposing to go along with the nominal  type:  observable. Objects can implement the observable contract, but are not expected to inject any asynchrony. The nominal static method Observable.from can be used to adapt an object that implements the observable contract to a nominal Observable type. Attempts to call the discoverable subscribe method will inject asynchrony using the micro task scheduler.

Please add an Observable.from and a Symbol.observer key. Have subscribe delegate to the Symbol.observer on the microtask scheduler (you can use a promise to get this behavior today).

**Comment by zenparsing** [comment]
Background question:  have we documented a use case (besides performance considerations) for synchronous subscribe?  What use cases would feel pain if subscribe was always queued?

**Comment by jhusain** [comment]
I think it's fair to say the only reason to allow synchronous subscription is performance. I know  @sebmarkbage is relying on sync subscription to deliver cached data quickly. Definitely open to reconsidering this, but we should bear in mind that scheduling on subscribe does not imply one schedule. If data is cached at the source (HTTP caching for example) and you have a series of combinators (flatMap) over the cached observable, then scheduling on subscription can easily degrade into scheduling on notification. In flatMap each item will create an Observable and therefore schedule. If all the data being retrieved is cached, this number of unnecessary schedules can easily multiply. Netflix has this case today: we cache at the source and subscribe to combinator chains over the cached data. This is one of the main rationales for treating Observanle differently than Promises - the cost of schedules for scalar values is per operation. The cost of schedules in vectors sources can Scale to the size of the vector.

**Comment by zenparsing** [comment]
Ah, right.  Once you allow allow for nested observables the cost of subscription is no longer constant:  when flattening a two dimensional stream the cost will be linear with the length of the outer stream.

After thinking about this for a while, I feel like it's pretty dodgy to force subscription onto the microtask queue at all.  Even with promises, we don't force asynchrony on the *initializer*:

```js
console.log("1");
new Promise(resolve => {
    console.log("2");
    resolve(null);
});
console.log("3");
// Logs 1, 2, 3
```

Forcing subscription onto the MT queue is equivalent in my mind to forcing the promise initializer onto the MT queue.  The only thing that matters is delivery, and if we are committed to synchronous delivery, I see no real advantage in having a public method which forces asynchronous subscription.

My intuition says that it would be better to forego this compromise, or at least hold out on it for a while.
