### ISSUE TITLE
Bike-shedding: `last()` should be `getLast()`

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#52]
Because it already exists in RxJS and it's popularly used as an *operator*, having a method named `last` doesn't make sense.

1. It doesn't imply that's taking any action to *do* anything, such as subscribe to the observable.
2. It seems to imply it's going to give you an Observable of the last value (especially because of prior art, and because of how it's worded: `last`, `first`, `map`, `filter`, etc.)

I think `getLast()` is slightly more explanatory about what it's doing. the "get" part implies some action will be taking to get the last value from the Observable and return it to you. And the only way anyone would get one value asynchronously would be with a Promise, so that's implied.

... I actually like `getLast(): Promise<T>` better than RxJS's `toPromise(): Promise<T>`... which I think sounds too much like `toArray(): Observable<Array<T>>`.

**Comment by ljharb** [comment]
fwiw, the name `last` seemed to go over well in the TC39 committee meeting, strictly over something like "getLast".

**Comment by zenparsing** [comment]
I'm not sure I really understand the rationale behind "last".  Why should the last value become the promise resolution?  Why not the first?  Why not the 15th?  Why doesn't "last" return an Observable for the last element?

In any case, it seems to me that "last" shouldn't be in the core proposal for now.  At least not until some fundamental design issues are ironed out.

**Comment by ljharb** [comment]
The idea is that the user chooses. If they want first, they'll call "first" to get a Promise for it; "last" for last, etc.

**Comment by zenparsing** [comment]
@ljharb That sounds great to me, but that actually argues against putting any one of these things into the core proposal.

**Comment by blesh** [comment]
FWIW, I'd like it more if none of them were in the core proposal.

@zenparsing: the final value of an observable is typically the "completion" value if there is one. This is used for things like `forkJoin`, which is Observable's equivalent to a `Promise.all`. Also `last` is commonly used to signal completion in a composable way. Other operators that emit only one value like `toArray` and `reduce` jive well with this pattern as well. `toPromise`in RxJS gives you a promise to the last value.

**Comment by blesh** [comment]
Why was this closed? (Just curious)

**Comment by RangerMauve** [comment]
It looks like @zenparsing is doing some cleaning and this was inactive for almost a month.

**Comment by blesh** [comment]
I still care about it... I guess I was just waiting for someone to say something. haha

**Comment by zenparsing** [comment]
@blesh So was I : )

Actually, it seems neither here nor there, since *currently* "last" isn't part of this proposal.  Someone could open an issue about adding it, though.
