### ISSUE TITLE
Polyfill minify issue

### ISSUE THREAD

**Issue by jeroencranendonk-wf** [zenparsing/es-observable#53]
I'm currently using the polyfill, and ran into a minor issue when minifying it with webpack 1.10.5, which uses UglifyJS 2.4. The parameter for the `catch` on [L324](https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L324) shadows the function parameter name `x`, which, although likely valid, confuses UglifyJS into outputting incorrect ES5 code.

**Comment by benjamingr** [comment]
Then file a bug against the offending party? The polyfill contains valid code.

**Comment by RangerMauve** [comment]
I assume you're compiling to es5 before uglifying?

**Comment by zenparsing** [comment]
Thanks @jeroencranendonk-wf for the report!  Looks like it would be cleaner code to have a different variable name anyway.  I've just made the change.

Also, I've removed the compiled-to-ES5 file from this repo.  You can either compile `src/Observable.js` yourself or check out [zen-observable](https://github.com/zenparsing/zen-observable), which is a minimal implementation of this spec and is published to npm.

**Comment by zenparsing** [comment]
@jeroencranendonk-wf Can we close this issue?
