### ISSUE TITLE
Move back to something like @@observer from @@observable

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#54]
In the short term it just makes for much a much better interop. 

If I'm the author of some random async library or the like, with `@@observer`, all I need to know to implement it is the basic interface of the Observer type, which is just three methods that are really straight forward.

However, if we stick with `@@observable`, then as the author of random async lib, until Observable lands in every JS engine I care about I need to completely reimplement an Observable or use a shim library.

I just think the story around the `Symbol.observer` method as an interop point is better. It also jives with other things that have been done like for Iterables.

**Comment by zenparsing** [comment]
> However, if we stick with @@observable, then as the author of random async lib, until Observable lands in every JS engine I care about I need to completely reimplement an Observable or use a shim library.

I'm not sure I understand the difficultly you are describing.  You don't need a polyfill with `@@observable`.

Creating an "observable-ish" manually:

```js
let someObservable = {
    [Symbol.observable]() { return this },
    subscribe(observer) {
        // implement it manually
    },
};
```

Consuming an observable-ish manually:

```js
someObservable.subscribe(...);
// or...
someObservable[Symbol.observable].subscribe(...);
```

What am I missing?

> It also jives with other things that have been done like for Iterables.

I don't see much equivalence between `Symbol.observer` and `Symbol.iterator`, frankly.  I've never been convinced of the duality there.

In fact, similarity to the iterator contract is one of the main reasons I proposed `Symbol.observable` in the first place.  It is much more in line with the intention of `Symbol.iterator`.

**Comment by zenparsing** [comment]
Another valid way to satisfy the `@@observable` contract:

```js
class Something {
    [Symbol.observable]() {
        return {
            subscribe(observer) { /* Implementation */ }
        };
    }
}
```

The only requirement of the contract is that something "observable":

1. Has a `Symbol.observable` method,
2. And that method returns an object with a "subscribe" method (which conforms to the contract).

**Comment by blesh** [comment]
... but that's not an "Observable". That's just a thing with a `subscribe` method. Your spec is pretty clear about the expected interface for an Observable. Isn't there a `forEach` function that returns a promise? What about "standard combinators"?

If you're only interested in exposing that `subscribe` method, why go through the extra step? Why not just move it up a peg and call it `Symbol.observer`?

**Comment by blesh** [comment]
In other words take this:

```js
class Something {
    [Symbol.observable]() {
        return {
            subscribe(observer) { /* Implementation */ } // <-- MOVE THIS
        };
    }
}
```

and make it this:

```js
class Something {
    [Symbol.observer](observer) { // < -- TO HERE AND RENAME IT
        /* Implementation */
    }
}
```

It could even be Symbol.subscribe if you like, the bike shedding of the Symbol name isn't a concern I have. I just liked the original design of `Symbol.observer` over `Symbol.observable` for the reasons I've outlined above.

**Comment by zenparsing** [comment]
> but that's not an "Observable". That's just a thing with a subscribe method. Your spec is pretty clear about the expected interface for an Observable. Isn't there a forEach function that returns a promise? What about "standard combinators"?

It's the minimal contract necessary to convert something "observable-ish" to Observable via `Observable.from`:

```js
let ish = {

  [Symbol.observable]() { return this },

  subscribe(observer) {
    observer.next(1);
    observer.next(2);
    observer.complete();
    return _=> {};
  },

};

Observable.from(ish).forEach(x => console.log("Got " + x));

// Got 1, Got 2
```

> If you're only interested in exposing that subscribe method, why go through the extra step? Why not just move it up a peg and call it Symbol.observer?

The rationale was covered here:

https://github.com/zenparsing/es-observable/issues/46#issuecomment-121834780

Why are we attempting to reverse the agreement there?  Can you provide an example which demonstrates how the `@@observable` approach is problematic?

Also, I very much doubt that programmers are going to want to implement the semantics of "subscribe" manually.  It just doesn't make sense when there are good, small, libraries around that will do that for you (e.g. an Observable polyfill, or Rx, or whatever).

**Comment by blesh** [comment]
But they're going to have to write an identical function to pass to the Observable constructor for the Observable they're returning, as what they're need to do to implement Symbol.observer... They get an observer, then they call next, error and complete on it, literally in both cases. It's just one way, they don't need to introduce any dependencies.

**Comment by blesh** [comment]
```
[Symbol.observable]() {
   return new Observable(observer => {
      /* logic here */
   });
}
```

Versus

```
[Symbol.observer](observer) {
  /* logic here */
}
```

**Comment by zenparsing** [comment]
Those two methods are not equivalent, by any stretch of the imagination.  In your first example, `observer` is a SubscriptionObserver, which is guaranteed to have all of the observer methods, in addition to `cancel` and `close`.  Also, the first example can return a cleanup action that will be guaranteed to run when the subscription is closed.

In the second example, all of those guarantees have to be written in manually.  The observer may not have an error or complete method (it may not even have a next method!).  There is no convenient way to register a cleanup function.

No programmer is actually going to want to write this stuff manually, given small and convenient libraries which can do it for them.

**Comment by blesh** [comment]
No imagination stretch required. The second example could also return an optional cleanup function. 

You're adding complexity for no benefit. If I'm a library interested in observables, I already have an observable implementation, you just need to give me the subscriber function. Why should we make every library that wants to support observables import an observable library? It's actually one thing wrong with promises right now. Every library pulls in its own impl. 

No one would need to write any guarantees. Can you supply an example of why they would? If I already have an observable implementation, because I want observable, that library would already have those guarantees implemented for me.

**Comment by blesh** [comment]
Maybe I'm dumb, though. Can you show me an example of where the @@observer method doesn't work?

**Comment by zenparsing** [comment]
> No one would need to write any guarantees. Can you supply an example of why they would?

Sure:

```js
let ish = {
    [Symbol.observer](observer) {
        observer.complete();
    }
};

ish[Symbol.observer]({
    next() {},
});

// Throws error, observer has no "complete" method
```

In effect, the method is useless without wrapping it in an Observable implementation.

I think we've been talking past each other.  If I understand correctly, you want the `Symbol.observer` method to *actually be the subscriber function*.  Is that right?  

That seems strange to me.  The subscriber function isn't intended to exist independently of the Observable that wraps it.

> Why should we make every library that wants to support observables import an observable library?

`Symbol.observable` doesn't require that.  You could just do:

```js
class Something {
    [Symbol.observable]() {
        return {
            subscribe(observer) { /* Implementation */ }
        };
    }
}
```

So I think the only objection here is to the additional indirection.  I need to think about this some more.

**Comment by blesh** [comment]
I see what you're saying. But I was thinking this was to be used differently.

Specifically, that the advised way to make an observablesque into an observable was to use `Observable.from` on it. That that, working concert with `[Symbol.observer]` was always the point. That would be used to switch between different implementations of Observable, as well. 

Like "you want your type to work with for..of? Implement Symbol.iterator" and "you want your type to work with Observable.from? Implement Symbol.observer" 

Either way it requires an observable implementation. Your way requires both the `ish` library author and the consuming author to have an observable implementation. My way only requires that the consuming author has one.

That's what I'm getting at. 

1. Higher complexity
2. Both parties need an observable implementation.

**Comment by zenparsing** [comment]
> Both parties need an observable implementation.

This is not true, as I think I've demonstrated a couple of times now.  The object returned from `Symbol.observable` *could* just be the minimal observable implementation (i.e. an object with a raw subscribe method) and that works fine with `Observable.from`:

```js
class Something {
    [Symbol.observable]() {
        return {
            subscribe(observer) { /* Assume observer is normalized and everything */ }
        };
    }
}
```

What we're trying to allow here is for arbitrary objects to define how they can be converted to an observable.  Providing a subscriber function is one way to do it, but there are others.  What if I want to compose over an observable and some combinators?

```js
class X {
    [Symbol.observable]() {
        return getStream().filter(...).map(...);
    }
}
```

Without the indirection, we have to do the subscription step manually, which feels awkward:

```js
class X {
    [Symbol.observer](observer) {
        return getStream().filter(...).map(...).subscribe(observer);
    }
}
```

The `Symbol.observable` setup feels a lot more intuitive:  if you want an object to be convertible to observable, then just provide a `Symbol.observable` which returns an observable.

As opposed to:  if you want an object to be convertible to observable, then manually implement a raw subscriber function method which is useless without a wrapping Observable implementation.

The only downside of `Symbol.observable` is one extra level of indirection in the case where you just want to provide a raw subscriber function.  I'm not seeing why eliminating the indirection in that case is worth making the API less intuitive.

**Comment by blesh** [comment]
It don't like it. You're not returning an observable. Would it need to implement forEach? Symbol.observable?  Map? Filter? Should it test as an observable?   Why not call it Symbol.objectWithSubscribeMethod? Because it's not an observable. 

I'm not trying to be a jerk, I'm just trying to get my point across. If it's to return an "observable", the ish author week need to use an observable implementation. 

Is there even precedent in JavaScript for a method that returns a shell of a type that isn't really that type? 

If the only thing I care about it's the subscribe function, why not just use that? That's what I'm saying.

**Comment by ljharb** [comment]
The precedent is iterators and promises - an iterable is something that has a function on `Symbol.iterable` that when called, returns an object that conforms to the expected interface: namely that it has a `next` method. Similarly, Promises accept anything "thenable" (something with a "then" method).

Having Observables also accept "subscribables" does seem somewhat consistent to me.

**Comment by blesh** [comment]
@ljharb ... `[Symbol.iterator]()` always returns a complete iterator though. With a `throw` and `return` method. I'm not sure promises and testing for a `then` function is really a good example of a solid design.

**Comment by domenic** [comment]
No it doesn't.

**Comment by blesh** [comment]
Really? There's actually precedent in JavaScript for returning a type that doesn't meet the entire contract? Gross.

Regardless, this is getting off track. I still think the current design is odd.  It's a stretch to say that returning something with nothing but a `subscribe` method I it is an "observable". 

If the subscribe method is *all* that's on there, it's all that's cared about, which means it could *be* the method. Why tack it on an object at all?

**Comment by zenparsing** [comment]
> Why tack it on an object at all?

I've already covered the advantages of the indirection in a couple of different posts, but here's another:  what if I want an abstraction to convert, not to an Observable, but to a subclass of Observable?

```js
class X {
    [Symbol.observable]() {
        return new ObservableSubclass(...);
    }
}
let x = new X();
let observable = X[Symbol.observable]();
// observable is an instance of ObservableSubclass
```

Beyond that, consistency with the iterable design is pretty important to me.  You might think many things about JavaScript are gross, but if Observable is going to be part of the built-in library then its API needs to "flow" with the rest of the standard library.  If there already is something called `Symbol.iterator` which returns an iterator for an arbitrary abstraction, then I think it's reasonable to assume that you would find an observable for an arbitrary abstraction with something called `Symbol.observable`.

I think a lot of the conflict between myself and the RxNext point-of-view comes down to the fact that I'm less concerned about micro-optimizing a particular JS library and more concerned with creating an API that harmonizes with the rest of the built-in library and JS idioms in general.

By the way, I'm not concerned about both producer and consumer wanting to "import" an Observable implementation.  After all, the point here is to add this to the standard library so that everyone has access to Observable, all the time!

**Comment by blesh** [comment]
I don't agree with what you keep saying you've "already been over", clearly. I understand you're frustrated. I don't think this design is consistent with the iterable design. And even though it's actually much, much easier for me to implement in RxJS Next, I don't think it's right. I'm not comfortable with it as a design decision. 

Iterable is a synchronous type. Observable is an asynchronous type, like Promise. I think the contract for interop should be something that accepts functions (like then), not something that provides another object. It should be more of the dual of iterable. 

If this design was like iterable as you claim, then all iterables would have a Symbol.iterable method. (Like Symbol.observable). Not Symbol.iterator.

I'm just unconvinced. You can think it's because I'm dumb. Maybe I am?

**Comment by ljharb** [comment]
`then` accepts *either functions or thenables*. If you pass it *any value with a `.then` method* then `Promise#then` will treat it as a "thenable".

Per your logic, should not the same should apply to Observables - passing `Observable.from` *any value with a `.subscribe` method* should cause it to be treated as a "subscribable"?

The variation between `Symbol.iterator` and `Symbol.observable` - namely, noun versus adverb - is worth thinking about. But I don't see how "returns an object with a subset of the contract" is anything but idiomatic JS at this point.

**Comment by zenparsing** [comment]
> I'm just unconvinced. You can think it's because I'm dumb. Maybe I am?

Please don't say things like this.  It implies that I don't respect your input, which I do.  Sometimes the end result of discussions like this is agreement to disagree.  I think we've both fully stated our cases, so I'm happy to leave it at that and let others read and form their own opinions.

> The variation between Symbol.iterator and Symbol.observable - namely, noun versus adverb - is worth thinking about.

Yeah, the naming is somewhat unfortunate here.  What we're calling "Observable" is actually more like an iterator, by interface.  It really ought to be a noun.

**Comment by ljharb** [comment]
Would `Symbol.observer` fit better?

**Comment by zenparsing** [comment]
@ljharb 

> Would Symbol.observer fit better?

No, because the "observer" is the thing that gets passed to "subscribe".  Observable is really functioning as a noun here.

The question we're wrestling with here is:  how should arbitrary objects be convertible to observables?

Under the current design (which I favor), the object implements a `Symbol.observable` method, which returns an observable:

```js
let obj = {
    [Symbol.observable]() {
        return new Observable(...);
    }
};
Observable.from(obj); // OK
```

But the `Symbol.observable` method doesn't have to return a full observable, it could just return something with a "subscribe" method.

```js
let obj = {
    [Symbol.observable]() {
        return { 
            subscribe(observer) {
                // Whatever
            }
         };
    }
};
Observable.from(obj); // OK
```

Under @blesh 's proposal, the arbitrary object that wants to be convertible to an observable would directly implement a "subscribe" method, using a symbol as the method key.  For clarity, let's call it `Symbol.subscribe`.

```js
let obj = {
    [Symbol.subscribe](observer) {
        // Do whatever
    }
};
```

If the object does something more complex with combinators and everything, it might look like:

```js
let obj = {
    [Symbol.subscribe](observer) {
        return getStreamFromSomewhere().filter(...).map(...).subscribe(observer);
        // Note the immediate call to "subscribe" above ^^^
    }
};
```

It's important to note that the `Symbol.subscribe` method here is generally not usable by itself.  For example, this would fail:


```js
let obj = {
    [Symbol.subscribe](observer) {
        observer.complete();
    }
};
obj[Symbol.subscribe]({
    next(v) {}
});
// Error: observer has no complete method
```

Generally speaking, the `Symbol.subscribe` method would require wrapping with an `Observable.from`-type implementation.

As far as I can tell, there's no fatal flaw either way.  I think that the `Symbol.observable` approach is more natural and less error-prone.  I think the indirection is useful and worth it, but @blesh disagrees.

**Comment by blesh** [comment]
> please don't say things like this. It implies that I don't respect your input, which I do. 

You just seemed frustrated at repeating yourself. As though I didn't understand what you were saying. I do. I'm just not sure it's the right thing to do.

**Comment by blesh** [comment]
In either case, it would be inadvisible not to use `Observable.from` on either what you got back from `[Symbol.observable]` or it `ish` itself (for `[Symbol.observer]`.

Because in both cases, you are not guaranteed to have an observable.

I don't think many library authors will make their types observable if they need to introduce a dependency. So they'll likely either not support it, or they'll hack out a Frankenobservable that's an object with a subscribe function on it.

**Comment by zenparsing** [comment]
> I don't think many library authors will make their types observable if they need to introduce a dependency. 

If it's part of the built-in library then there is no external dependency required : )

**Comment by RangerMauve** [comment]
Isn't it similar to how Promises require polyfills to work in certain envrioments? I think it's reasonable enough to assume that developers wanting to use observables would be OK with including a polyfill for environments that don't support it. It just means that the spec will need to be simple but specific enough that multiple implementations could play nice with each other as long as they respect the interface.

**Comment by blesh** [comment]
Maybe. I think my concerns are adequately voiced.

**Comment by zenparsing** [comment]
It would be good to capture these controversial aspects someplace.  Maybe a separate markdown doc with links to the GH issues, and then I can link to that doc from the README.
