### ISSUE TITLE
Question about Observable.from and @@observable

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#55]
If I have an object:

```
var foo = {
  [Symbol.observable]() {
    return {
       subscribe(observer) {
          /* do things */
       }
    }
  }
};
```

and I want to use `Observable.from`... do I:

1. `Observable.from(foo)`
2. `Observable.from(foo[Symbol.observable])`

... I'm assuming 1.  But If someone pulls out a value from `foo[Symbol.observable]()` and sticks in a variable, and does whatever with it, should they be able to pass it to `Observable.from()`? Will `Observable.from` have to check for a `subscribe` function on anything passed to it and call that thing?

Right now I have `Observable.from` checking:

1. Is it an Iterable?
2. Is it a Promise?
3. Does it have `[Symbol.observer]`?
4. It's not convertable.

But I wonder with `[Symbol.observable]` if I'll need to do this:

1. Is it an Iterable?
2. Is it a Promise?
3. Does it have `[Symbol.observable]`?
4. Does it have a `subscribe` method?
5. It's not convertable.

Step 4 doesn't *seem* like it would hurt much, but I'm just curious if this is the intention. Should I be able to pass any object with a `subscribe` method to `Observable.from`?

**Comment by RangerMauve** [comment]
What do Iterators do in that situation?

**Comment by blesh** [comment]
@RangerMauve: They convert to an Observable. Similar to an `Observable.fromArray` or the like, if you're familiar with Rx.

**Comment by RangerMauve** [comment]
Sorry, I think I wasn't clear enough. I meant to say what do iterators do when you call `[Symbol.iterator]` on the result of `[Symbol.iterator]`.

**Comment by blesh** [comment]
@RangerMauve ... I don't understand your question still I think. I'm sorry.

If you call `[Symbol.iterator]` on an object that has it, you'll get back an `iterator`, to my knowledge, `iterator` instances do not (usually) have a `[Symbol.iterator]` on them. Maybe in some really rare custom cases they do?

This particular issue was just for clarfication about how `Observable.from` should behave, it's unrelated to my other issue, which I've closed.

**Comment by RangerMauve** [comment]
Err, I think I misunderstood something along the way, too. :sweat_smile: Disregard what I said thus far.

In my opinion, I like the idea of adding step 4 in your second example since it seems kind of similar to the idea of things `thenable` in regard to promises.

**Comment by domenic** [comment]
All iterators in the spec have `[Symbol.iterator]` on them.

**Comment by blesh** [comment]
> to my knowledge

Heh... which is apparently lacking. Thanks for pointing that out, @domenic

I'd be curious what the usefulness of that is.

**Comment by blesh** [comment]
Also, thank you @domenic for pointing out where I was mistaken about iterators in the other thread. I conflate iterators and generators frequently.

**Comment by zenparsing** [comment]
> I'd be curious what the usefulness of that is.

The purpose is to make iterators themselves compatible with `for-of`, array destructuring, etc.

I've strived for consistency between the iterator design and this observable design, so `Observable.prototype` has a `[Symbol.observable]` method which returns `this`.

Right now, `Observable.from` does roughly:

1. If the object have a `Symbol.observable` method, then
    1. Get an object `x` by calling that method.
    1. If the constructor of `x` is Observable, then return `x`.
    1. Return `new Observable(sink => x.subscribe(sink))
1. Assume that the object is iterable and return an observable over that iterable.  (If it's not iterable it will end up erroring out when subscribed to.)

The idea is that promises could be made convertible in the spec by adding `Symbol.observable` to them.

Maybe step 2 should be changed to throw early instead?

**Comment by blesh** [comment]
> The idea is that promises could be made convertible in the spec by adding Symbol.observable to them.

True enough. However, really anything that is "thennable", iterable, or observable should "just work" in Observable.from, IMO. Whether or not Symbol.observable is implemented, it's really straightforward to know what to do with those types to make them observable, since they're consistent.

Anyhow, my question stands: 

> Should I be able to pass any object with a `subscribe` method to Observable.from?

In the other issue I just closed, it was mentioned that all anyone would need to do is return the ["minimal Observable"](https://github.com/zenparsing/es-observable/issues/54#issuecomment-138341302) and it should work. Other items in the Observable contract were not required (such as `forEach` or `Symbol.observable` or `filter` or `map`). Should I be testing for "subscribable" as well?


This really goes back to why I thought @@observer was better, but that seemed a losing battle.

**Comment by zenparsing** [comment]
> In the other issue I just closed, it was mentioned that all anyone would need to do is return the "minimal Observable" and it should work. Other items in the Observable contract were not required (such as forEach or Symbol.observable or filter or map).

Yep.  So that's a good point and I'm glad you brought it up.  A well-defined observable should have at least a "subscribe" method and a `Symbol.observable` method, similar to how a well-defined iterator should have a "next" method and a `Symbol.iterator` method.

This definitely weakens my argument that no Observable implementation is wanted on the provider side, so thanks for pointing that out.

Still, the presumed end result of this effort is that everyone has access to a built-in Observable implementation, so the requirement is not a problem for me.

Again, similarity with iterables/`Symbol.iterator` is an overriding concern here.  Is there a reason why you think that maintaining this correspondence is not important, or that it's flawed?

**Comment by domenic** [comment]
FWIW I think maintaining the correspondence is very important. Although, it is confusing that the correspondence is between observable and iterator, instead of between observable and iterable. It makes we wonder what the iterable equivalent is.

**Comment by blesh** [comment]
>  Is there a reason why you think that maintaining this correspondence is not important, or that it's flawed?

@zenparsing I think @domenic said it for me:

> it is confusing that the correspondence is between observable and iterator, instead of between observable and iterable.

**Comment by zenparsing** [comment]
> it is confusing that the correspondence is between observable and iterator, instead of between observable and iterable

I'm not sure what the right answer is here, but I think maybe we just have an unfortunate naming situation that makes things confusing.

An "iterable" is something that can be iterated over.  An "iterator" is the object which provides the interface for iterating.  Iterators are "iterable".

An "observable" is something that can be observed.  An "Observable" (capital O) is the object which provides the interface for observing.  Observables are "observable".

It's like we're using the word "observable" for both the thing which provides the capability and the capability itself.

Maybe it should be "Observerator" or something : )

**Comment by domenic** [comment]
I was thinking about suggesting that, actually. It seems like a good idea to be honest. Although maybe it could just be ameliorated with an FAQ or similar.

What is an example of a lowercase-o observable, analogous to array/map/set for iterables?

**Comment by zenparsing** [comment]
A promise, in principle.

I'm not very good with practical examples.  @blesh can you think of some other lowercase-o observables?

**Comment by ljharb** [comment]
So an "iterable" is so because it has `Symbol.iterator` which provides a function that returns an "iterator". Arrays/Maps/Sets/Strings are all "iterable".

An "observable" is thus so because it has `Symbol.X` which provides a function that returns an "X" - where "X" is, in the current proposal, an "Observable" (capital O). Promises/thenables, eg, are all "observable".

So, we need a good (different) name for the object which provides the interface for observing - would "observer" work? Just like an iterator is how one iterates, an observer would be how one observes. Then it'd be `Symbol.observer`, and the similarity to `Symbol.iterator` would provide an intuitive and hopefully correct conceptual understanding to users.

**Comment by blesh** [comment]
@zenparsing, pretty much anything that can be represented, in total, as any number of values over any amount of time. Provided that it is a concise representation, of course. 

Iterables, generators, iterators of promise (If they had a type discernable from plain iterators they could flatten into one stream), promises, arrays, strings, Streams, EventSources, Sockets, MessageChannels. Not so much for DOM events, because they're not really represented as any type of collection or singular object.

Any of the above could implement a Symbol.observable method natively, I suppose.

Is that what you're asking? 

I mean realistically, I'm not going to check for all of those in RxJS Next's `from` method, of course. I'll only look for observablesque values, promises and iterables.

**Comment by zenparsing** [comment]
@ljharb Rx uses "Observer" to mean the thing which gets passed to subscribe.  But following the line of thought, we *could* name that a "subscriber":

An "observable" is something that can be observed. An "observer" is the object which provides the interface for observing. The object which gets passed to subscribe and receives the data is a "subscriber".

That seems to work out pretty well, but unfortunately it conflicts with the current terminology in the Rx world.

**Comment by blesh** [comment]
> @ljharb Rx uses "Observer" to mean the thing which gets passed to subscribe. 

RxJS Next uses a "Subscriber", technically, but same idea. It's the Observer + Subscription in one class.

**Comment by blesh** [comment]
@zenparsing I think the concensus here is this:

1. `[Symbol.observable]()` should return a (lowercase "o") _observable_.
2.  (lowercase "o") observables __must__ have a `subscribe()` and `[Symbol.observable]()` implementation.

Also I think in the `README` `Symbol.observable` was a property last time I looked, it seems it should be a method to be consistant with `Symbol.iterator`

I'm closing this with the assumption that what I've asserted in this comment is correct. If I'm wrong, @zenparsing, please correct me and I'll reopen and discuss.

**Comment by zenparsing** [comment]
> Also I think in the README Symbol.observable was a property last time I looked

Thanks, fixed.

**Comment by blesh** [comment]
I've edited my comment above slightly to include the bit about Observable.from.
