### ISSUE TITLE
Iterating observables is weird in a coroutine

### ISSUE THREAD

**Issue by hollowdoor** [zenparsing/es-observable#56]
After watching the video by Jafar Husain about observables I decided to try to implement `for on` like functionality using yield.

As you can see it's rather bad, but it works. The main problem is I copied the style that's often used in these types of coroutine libraries, and it turned out it was rather hard to make an observer that can be called more than once from these types of coroutines.

```javascript
spawn(function * (){

    var ev, index = 0;
    var click = event('#clickme', 'click');
    //click yields the current event
    while(ev = yield click){
        //Yield to a log just because.
        console.log(yield ev);
        if(++index > 2){
            //Cancel the above click subscription by
            //calling cancel inside the coroutine.
            return;
        }
    }

    return ev;
})().then(function(value){
    console.log('final value = ', value);
}, console.log);

function event(elem, event){

    var so = new Observable(function(observer){
        var listener = function(value){ return observer.next(value); },
            el = document.querySelector(elem);

        el.addEventListener(event, listener, false);

        return function(){
            el.removeEventListener(event, listener, false);
        };
    });


    so.subscribe = function(observer){
        //I don't know when the subscription starts
        //so I'll set a started state here.
        //To bad this only allows one subscription.
        this.started = true;
        return Observable.prototype.subscribe.call(this, observer);
    };
    return so;
}

/**
 * Simple spawn
 * Based on common implementations of pseudo coroutines.
 */

function spawn(cb){
    return function(){

        return new Promise(function(resolve, reject){
            var gen = cb.next ? cb : cb(),
                cancel;
            function fn(next){

                if(next.done){

                    if(cancel) //cancel the one subscriber
                        cancel();
                    return resolve(next.value);
                }

                //I don't know how to detect Observables yet
                //Please ignore this.
                if(next.value.constructor &&
                    'Observable' === next.value.constructor.name){

                    //If we continue passed here the subscriber
                    //will subscribe again making the loop
                    //build up exponentially so
                    //return on started equals true.
                    if(next.value.started){
                        return;
                    }

                    //next.value is an Observable
                    //An aggregator of cancel functions would be better,
                    //but a single call is simpler for illustration.
                    cancel = next.value.subscribe({
                        next: function(value){
                            fn({value: value, done: false});
                        },
                        error: function(e){
                            gen.throw(e);
                        }
                    });
                    return;
                }

                //Do some promise.then, and thunk calling here.

                //Normal values are sent right back.
                try{
                    fn(gen.next(next.value));
                }catch(e){
                    fn(gen.throw(e));
                }
            }

            fn(gen.next());
        });
    }
}

```

If I wanted to I could add an aggregator of cancels to have more than one observable, but I couldn't add more than one subscriber per observable.

I'm wondering if this is a limitation of the Observable, or if I messed up in my experiment. I haven't found any methods in this proposal that would make this kind of thing easier. The `for on` is down the road, but even then I think it might be useful to have these pseudo coroutines around to supplement the `for on`, and async/await. Especially if they have observable compatibility.

Promises won't work because if there's a mousemove in there all hell will break lose.

**Comment by zenparsing** [comment]
Hi @hollowdoor .

I don't think you want to re-subscribe to the observable on every loop iteration (and therefore you don't want to yield an observable to the spawn runner).  You really want to subscribe once and then let the generator consume each event out of the stream.

I think what you want to do is more along these lines:

https://gist.github.com/zenparsing/ac5abd3c4f45659b0ba2

What do you think?

**Comment by hollowdoor** [comment]
Not really. :)

I want to be able to yield multiples of different events so I can build a state machine. Kind of like this example http://syzygy.st/javascript-coroutines/#demo but with spawn like semantics instead.

It would be nice to be able to yield multiples of the same too. To capture a double click, but possibly a delayed double click.

I want to do this:

```javascript
var any = event('#someCrazyElement', 'click blur move'),
    click = event('#clickme', 'click');
    while(ev = yield click){
         while(ev2 = yield any){
            //check which one of any here
            while(ev = yield click){
                 //interupt any events
            }
        }
    }
```

It's true that I do not want to resubscribe on every iteration of a specific loop, but I'd like to have a new subscription at an appropriate point. I'm coming close to figuring something out, but I wanted to see if there is some other way to do it with the current proposal of Observable without extending it.

It appears this proposal for Observable by it being an observable pusher it has the same problems as original streams in nodejs. Flow of data is not so easily pulled right when it's needed. For instance the way highlandjs does it is there is an actual pull method with a callback. That's using streams though, but the same idea applies as Observable has a similar concept of flowing data from a source to one, or more destinations.

**Comment by zenparsing** [comment]
> It appears this proposal for Observable by it being an observable pusher it has the same problems as original streams in nodejs.

For modeling a pull-based source, yup.

The idea is that sometimes you want to receive pushes, and sometimes you want to pull.  Observable is appropriate for pushed-oriented data sources and consumers.  Async iterators are appropriate for pull-oriented data sources and consumers.  Check out:

https://github.com/zenparsing/async-iteration

It introduces `for await (...) {}` loops which might be what you're looking for.

You'll be able to convert an observable to an async iterator, so things like this would work:

```js
async function fn() {
    let clicks = listen(element, "click");
    for await (let event of buffer(clicks)) {
        console.log("click!");
        await doSomethingAsync(event);
    }
}
```

The `buffer` function would convert the observable to an async iterator, buffering any events which come in before the consumer requests the next one.

What do you think?

**Comment by zenparsing** [comment]
It's also possible to compose more advanced observable streams from simpler ones to get a single stream that you want.  You can do mouse-dragging stuff like:

https://github.com/zenparsing/es-observable/blob/master/demo/mouse-drags.js

Where most of those functions (like takeUntil and switchLatest) would be provided by a library.

**Comment by hollowdoor** [comment]
Wow I was not familiar with `for await`. Isn't that close to the same as `for on` though? I'm not sure how that gets me from push to pull in a pseudo coroutine like spawn. Maybe yielding a regular es generator wrapped around an observable?

For your mouse drags example I noticed that that can already be done with `observable.forEach` with a promise returned instead of a cancel function. That works, but it still won't compose to spawn.

**Comment by hollowdoor** [comment]
Well it looks like the mouse drag example is not quite the same as `forEach`. It still looks like it won't work in this one case.

**Comment by zenparsing** [comment]
> Isn't that close to the same as for on though?

They're separate proposals; my preference is to only go with `for await`.

Do you need coroutines, if you have `for await`?  You could rewrite your first example to something like:

```js
async function fn() {
    let index = 0;
    
    for await (let ev of toAsyncIterator(event('#clickme', 'click'))) {
        console.log(ev);
        if (++index > 2)
            return;
    }
}
```

**Comment by hollowdoor** [comment]
No I don't need coroutines, but a coroutine can do a lot more already. It would be better to say I like coroutines.

If set it up correctly I can yield a callback function of one arity, a promise, an array/object of promises to resolve in parallel, another generator, and even an array of streams. Right now a coroutine is more flexible with less code for users than the `async await` proposal.

I wouldn't want to say there's a burden on the implementation of the proposal just because I like a certain way of doing things, but I'm guessing a particular standard gets started because someone likes it.

async/await doesn't have to do all of the things a coroutine does, but that's why coroutines exists. To fill a niche of composability.

I will admit though that `for await`, or `for on` are one solution, and it's actually really cool. It's something I'll definitely be using if one of those gets into the standard. I'm still looking for a way to do it where I can compose into a coroutine.

**Comment by hollowdoor** [comment]
After some thought my experiment might have been premature. The best I've come up with is simulating an Async Iterator with a timer for polling.

The facilities are just not there in Javascript as it is to do this this kind of thing, and still have good performance except maybe when there is just one asynchronous operation to wait for. Also I admit now that plain Observers are not good for this kind of thing.

I'll leave this open for a short while. While I give some thought to what I've discovered. Maybe I'll figure something else out.

**Comment by hollowdoor** [comment]
I think that I'm going to have to start liking observable array like methods, or just regular events.

I patiently await from async for. :)
