### ISSUE TITLE
Should forEach's returned promise resolve with the last value from the stream?

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#57]
That would be consistent with other API's dealing with Observables as scalars. It does introduce some state to that method, but it would make it's resolution more useful.

Basically, in RxJS, in other situations where you might convert an Observable to a promise, you're resolving that promise with the last value emitted from the observable.

I'm on the fence as to whether or not I care about this feature, but I noticed it while looking at the implementation of it today, and I thought it would bring it up.

**Comment by zenparsing** [comment]
My initial thought was to make forEach as similar as possible to Array.prototype.forEach, which of course doesn't return the last value.  I have it resolve with the completion value, which in almost every (all?) cases will be "undefined", as with Array.

Do you think it adds enough value to make up for the divergence from Array?

**Comment by blesh** [comment]
> Do you think it adds enough value to make up for the divergence from Array?

No. After speaking with @jhusain about this, I think we can drop it.
