### ISSUE TITLE
Is Observable.of redundant?

### ISSUE THREAD

**Issue by Alpacatty** [zenparsing/es-observable#59]
*(note: I am neither a professional nor have ever done more with a spec than try to read it. If I'm massively overlooking something and this is just plain stupid, I apologize.)*

I'm not really sure about the value of `Observable.of`.
Anything you could put in `Observable.of` you could put in `Observable.from` surrounded by a pair of `[]` and it'd function exactly the same.

You don't save on unnecessary intermediate arrays, as [zenparsing/zen-observable](https://github.com/zenparsing/zen-observable) puts all the arguments into one anyway using a rest parameter, and then just follows the exact same logic `Observable.from` uses to handle arrays.

Ignoring the fact that "from" is a longer word than "of", does saving 2 characters really justify the extra API method?

(and of course, `Observable.of` limits you to 255 arguments ergo only 255 values can be emitted :wink:)

**Comment by ljharb** [comment]
`Array.of` exists, and the similarity to `Observable.of` is useful.

**Comment by blesh** [comment]
`Observable.from` has to do a bunch more checks to see what it's dealing with. `Observable.of` does not. So `Observable.of(1, 2, 3)` is going to be a more efficient way to do `Observable.from([1, 2, 3])` no matter how you slice it.

**Comment by benjamingr** [comment]
Observable.of also has the advantage of being easier to statically analyze, but yeah - the major thing here is that the Observable API can get `.of` if Arrays got it. Arrays got it - so it makes sense to give users the same familiar API.

**Comment by Alpacatty** [comment]
> Array.of exists, and the similarity to Observable.of is useful.

---

> Observable.of also has the advantage of being easier to statically analyze, but yeah - the major thing here is that the Observable API can get `.of` if Arrays got it. Arrays got it - so it makes sense to give users the same familiar API.

True, consistency with familiar relates APIs tends is good.
It's just that the main use cases for `Array.of` seem to be:
* **Subclassing**, where you can't use the array literal to get an instance of the `ExtendsArray` you defined, so you have to do `ExtendsArray.of(1,2,3,4)`

This shouldn't be a problem with Observable, as it doesn't have its own literal and `ExtendsObservable.from(source)` works just as well as `Observable.from(source)`.

* **Types that constructed later**, e.g. `const cast = (constructor, value) => constructor(value)`, where `Array.of` can be used as the first argument, since the `Array` constructor is weird and doesn't act like you'd expect it to given how `String`, `Number`, etc. behave.

Still a valid use case for Observable, but nothing prevents you from just passing `(...items) => Observable.from(items)` which is fairly simple and intuitive.

> `Observable.from` has to do a bunch more checks to see what it's dealing with. `Observable.of` does not. So `Observable.of(1, 2, 3)` is going to be a more efficient way to do `Observable.from([1, 2, 3])` no matter how you slice it.

Ignoring the polyfills included (the one for Symbol, plus a fallback for browsers that don't support iterators so methods still work on arrays that's only included in the version in zenparsing/zen-observable but not the Observable.js in this repo) and the fact that `Observable.from(x)` throws a `TypeError` when `x == null` which would've been thrown anyway when checking for `x[Symbol.observable]` if `x == null`, there's only two ways in which `Observable.from` and `Observable.of` differ:

1. `Observable.from(x)` checks for `x[Symbol.observable]`. This is indeed less efficient than not checking for it, but since it doesn't impact the speed at which `x` is looped over, its impact should be negligible.

(Of course `Observable.from` does different stuff when `x` is an observable rather than iterable, but since that won't be the case in `(...items) => Observable.from(items)` we'll just ignore that)

2. `Observable.from` uses a `for...of` loop, `Observable.of` uses a `for` loop. However, the loop from `Observable.from` can just be copypasted in place of the one in `Observable.of` and `Observable.of` would behave exactly the same.
Being a recent addition, `for...of` is less well optimized, but it can easily be transpiled down to a `for` or `for...in` loop and any project where the performance of `for...of` at the time of writing is important is probably transpiling ES2015/ES2016 down anyway.

**Comment by zenparsing** [comment]
@Alpacatty There's also the Observable-of-one case.  This:

```js
Observable.of(oneThing);
```

Feels more intuitive than saying:

```js
Observable.from([oneThing]);
```

Given that it has the value described above as well as the consistency with Array, I think `Observable.of` is justified.
