### ISSUE TITLE
Should Observable.of and Observable.from emit synchronously?

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#60]
For performance and consistency. It seems weird to say "If you create an observable this way, it's synchronous, but if you create it this other way, it's not."

Especially Observable.of, that is basically creating an array. It seems weird to create an array that you iterate over asynchronously. Likewise, Observable.from(array) being asynchronous doesn't make sense.

People need to learn functional programming and immutable state.

**Comment by blesh** [comment]
>People need to learn functional programming and immutable state

Meaning I'm against fearing "Zalgo", and more for teaching people how to fish.

**Comment by zenparsing** [comment]
> Meaning I'm against fearing "Zalgo", and more for teaching people how to fish.

I'm sympathetic, but we've had these discussions several times and it always comes out the same way.

Realistically, if we want `Observable.from` and `Observable.of` to *not* do the "next job" thing, then we'll have to go back to having two different subscribe functions.

**Comment by blesh** [comment]
Or something like `subscribeOn`. Just some way to set the behavior

**Comment by zenparsing** [comment]
> Or something like subscribeOn

It's a bit of a catch-22.  

Users will reach for the "easy-to-reach-for" method, which in this case will be `subscribe`, and which gives them no zalgo-protection.  You might as well just not have the extra method.

On the other hand, if you make async subscription easy to reach for instead (like we had previously with `subscribe`/`Symbol.observer`), then you'll annoy those that want synchronous subscription, but even more importantly, you'll create a footgun in situations where the end-user actually *does* need sync subscription (like registering DOM event handlers and such).

**Comment by blesh** [comment]
Meh, I give up on this one. I'm more concerned about the cancellation function. This isn't of much consequence, as people can easily override this behavior to get what they want or create other "from" methods. I do think it's unfortunate, but no more unfortunate than I think the industry's hang ups with "Zalgo" are.

**Comment by zenparsing** [comment]
Reopening this one, not because I've changed my mind, but because I think this issue needs to be left open as a reflection of the design controversy.

**Comment by blesh** [comment]
:+1:

**Comment by chicoxyzzy** [comment]
looks like this issue might be closed in favour of https://github.com/zenparsing/es-observable/issues/88 right?

**Comment by zenparsing** [comment]
From and of are now synchronous.
