### ISSUE TITLE
Idea: Return a thennable subscription object from `subscribe()`

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#61]
This relates to #48, I had a thought today:

We could remove `forEach` if the returned `subscription` object was also "thennable". It wouldn't be a *promise* necessarily, because it obviously would have an `unsubscribe` method, but the semantics of `then` for promise would obviously need to be the same. I don't think I'd remove the `error` and `complete` callbacks, because they allow the developer to handle those events immediately, rather than scheduling them, and I think it's unlikely that anyone would really use the subscription like a promise. I was thinking this would be most useful with `await`, and to lean up the API by getting rid of `forEach`.

**Comment by RangerMauve** [comment]
What would it resolve to?

**Comment by blesh** [comment]
@RangerMauve The same as the promise returned by `forEach`... the completion of the observable (and it would error for the error of the same).

**Comment by RangerMauve** [comment]
@blesh Ah, so it's meant to perform the same action as the return of forEach, not replace forEach. I think it makes sense.

I could see that as being a good reason for giving up the return being a function.

**Comment by RangerMauve** [comment]
Though I would suggest returning an actual promise rather than a thennable since it seems most native APIs that return promises return actual ones and not just thennables.

**Comment by benjamingr** [comment]
This is precisely what I've been asking for all along, big +1. 

(It'd be a promise, promises can have additional properties - we can call it a promise subclass)

**Comment by RangerMauve** [comment]
Would the promise resolve early if the subscription ended, or will it resolve when the observable completes regardless of whether that particular subscription is active?

**Comment by blesh** [comment]
Typing this makes me cringe a little, because I've never really liked the idea of a "cancellable promise", but it could *technically* duck-type as a cancellable promise, if the [spec for that looks like this](https://github.com/domenic/cancelable-promise/blob/master/lib/cancelable-promise.js)

This would not necessarily tie the specs together, but it would mean some API similarities between the two

```js
interface Subscription {
   isUnsubscribed: boolean;
   cancel(): void
   then(successFn, errorFn): Promise
}
```

**Comment by blesh** [comment]
> Would the promise resolve early if the subscription ended, or will it resolve when the observable completes regardless of whether that particular subscription is active?

If you ended the subscription, the promise wouldn't resolve at all. It would effectively be "cancelled"

**Comment by RangerMauve** [comment]
I dunno. That sounds _*really*_ gross.I think that my proposition with having the cancellation of the subscription resolving the promise is more likely to gel with other APIs and make this spec easier to accept. What if cancelling the subscription would make the promise reject to signify that it didn't reach the end of the observable?

**Comment by zenparsing** [comment]
See https://github.com/zenparsing/es-observable/issues/20#issuecomment-108073067 for previous discussion on this idea.

The big objection was that it gets weird when the observer has an error handler or complete handler.

```js
let p = observable.subscribe({
    next(v) {},
    error(e) {
        return "error?";
    },
    complete(v) {
        return v + 1;
    },
});
```

You get mixed error handling semantics.

Again, my perspective is probably not going to align well with the Rx team here.  I think that `subscribe` will be primarily used for implementing combinators and `forEach` will be primarily used by the "end-user".

This is also why I'm not particularly interested in overloading the arguments to `subscribe`:  I think end-users will reach for `forEach` instead.

**Comment by blesh** [comment]
> I dunno. That sounds really gross.

Well, that's a cancellable promise. :\

The problem is Observables have three types of terminal events:  

1. success: Producer tells Consumer that it's completed without error.
2. error: Produce tells Consumer it's completed because of an error.
3. cancellation: Consumer tells Producer it doesn't want anymore values.

In scenario 3, the Consumer doesn't need an additional event to tell it what it already knows: That it initiated the termination of the event stream.

So it doesn't make any sense to have the Promise's success path fire for both scenario 1 and 3, because it would create ambiguity as to what that event firing really meant.

**Comment by blesh** [comment]
>  and forEach will be primarily used by the "end-user".

I really doubt that.

```
observable.subscribe(x => log("next", x), err => log("error", err));
```
vs
```
observable.forEach(x => log('next', x)).then(null, err => log('error', err));
```

... not to mention that if you accidentally write code that throws in your error handler in the second example above, it's going to get swallowed.

```
observable.forEach(x => log(x)).then(null, (err) => { throw 'oops!' });
```

In the observable `.subscribe()` error handler it will be re-thrown if it's not handled, so the developer will at least *know* that something went wrong.

**Comment by blesh** [comment]
If the goal is simply to allow cleaner use of `await`, using some form of promise return makes sense. But I'd personally steer people away from using `forEach` as it currently stands.

**Comment by RangerMauve** [comment]
Another thing to consider is that promises resolve asynchronously, whereas AFAIK the complete and error callbacks in the subscriber get called synchronously.

**Comment by zenparsing** [comment]
What happens here:

```js
let p = observable.subscribe({
    next(v) {
        throw new Error("boom");
    },
});
```

Does the error crash the program, or does it get stored as a rejection in `p`?  It can't crash the program (because someone might add an error handler to `p`).  If it gets stored as a rejection, then it's just the same as promise errors getting "swallowed".

By the way:

> observable.subscribe(x => log("next", x), err => log("error", err));

I believe that TC39 rejected the argument overloading you're using here a couple of months ago.  We'd have to introduce another method name anyway.

> observable.forEach(x => log('next', x)).then(null, err => log('error', err));

Actually, I was thinking more along the lines of:

```js
await observable.forEach(x => log("next", x));
```

which is pretty sweet.

The advantage of `forEach` for end-use is that the completion and error handling semantics align with promises, and by extension `await` and async functions.  If you really don't want to use promises though, then you shouldn't be trying make `await` meaningful for non-promise things.

**Comment by benjamingr** [comment]
>  If it gets stored as a rejection, then it's just the same as promise errors getting "swallowed".

I'd just like to point out that promise errors don't get swallowed. They get handled, and unhandled rejection detection exists pretty much everywhere now. The "swallowed promise" thing is a thing of the past really, we should treat it as such. 

-----------

To be fair, I do see the argument of two separate APIs (subscribe and forEach) and I do see how `.forEach` gets cancellation as it lands in promise land. There is also a huge appeal for having a single method. In dart, everything is implemented in terms of `listen()` (our subscribe) but it has a `asFuture` method.

**Comment by zenparsing** [comment]
> They get handled, and unhandled rejection detection exists pretty much everywhere now. The "swallowed promise" thing is a thing of the past really, we should treat it as such.

Yay, thanks for saying that!  I wanted to mention something to that effect but forgot to.

**Comment by blesh** [comment]
> I believe that TC39 rejected the argument overloading you're using here a couple of months ago.

I don't follow.

> I'd just like to point out that promise errors don't get swallowed. They get handled, and unhandled rejection detection exists pretty much everywhere now. The "swallowed promise" thing is a thing of the past really, we should treat it as such.

I don't think you get what I'm saying. It's "swallowed" in that it can't be caught or handled by any code anywhere else:

```
window.onerror = err => {
  console.log('Uncaught error: ', err);
}

Promise.resolve('test').then(x => { throw 'bad' });
```

At *best* you get them logged out to console to be helpful. At worst (in RSVP for example, or with some browser's native implementations) they don't do anything but silently fail.

**Comment by blesh** [comment]
@zenparsing I'm actually disconcerted by the idea that you thought `forEach` is what everyone would use. I was actually stunned by that comment. I was thinking of it purely as a concession for fans of Promise and await.

**Comment by benjamingr** [comment]
@blesh I'm a 'fan of await'. I'd love to use subscribe with it, I anticipate for example people will be using observables to write their build scripts often, and await is really helpful in several places in my code here. 

> I don't think you get what I'm saying. It's "swallowed" in that it can't be caught or handled by

Promises don't get swallowed anymore. In order to not hijack this discussion to a place none of us wants it to go, I've made a gist illustrating that here: https://gist.github.com/benjamingr/f7a1d00248718dcc36a1 we can continue discussion there.

**Comment by blesh** [comment]
Fine, staying on topic:

### View changes in a "SPA"

Let's say you have a "single page application" as so many of us do now, and during a View load, you set up some Observable, using `forEach` that is supposed to get 5-10 messages over an indeterminate period (let's say it's usually very fast, but sometimes it's slow)... if you do `await myObs.forEach(doThings)`, you have no way to cancel that observable's subscription. Why would you want to do that? Because the user just clicked a link to a new view, and you no longer care about that data anymore. But now it's coming, whether you like it or not, and it will be processed.

If the `subscription` were a thennable object, you'd be able to use both `await` *and* cache the subscription to be torn down on view change:

```js
let subscription = null;

function onViewLoad() {
   subscription = getSomeObservable.subscribe(updateView)
   await subscription;
   notifyViewSubscriptionComplete();
}

function onViewUnload() {
  if(subscription)  subscription.unsubscribe();
}
```

### cleaner error handling

If you use `await forEach` everywhere, to handle errors, most likely you're going to be using a try/catch block, I assume?

```js
try {
  await someObservable.forEach(handleNext)
  handleCompletion();
} catch (err) {
  handleError(err);
}
```
as opposed to:

```js
someObservable.forEach(handleNext).then(handleCompletion, handleError);
```

or better:

```js
someObservable.subscribe(handleNext, handleError, handleCompletion);
```

The last one is "better" because it's actually going to give you the ability to cancel the subscription. What I'm proposing is this:

```js
let sub = someObservable.subscribe(handleNext, handleError, handleCompletion);
await sub;
```

**Comment by blesh** [comment]
I'm willing to flip this proposal around too..

What if we remove `subscribe` and keep `forEach` but have it return a Cancellable Promise?

**Comment by blesh** [comment]
If we remove subscribe and keep `forEach` with a cancellable promise, I think that would conclude all discussion at #48, as well.

```js
let sub = obs.forEach(nextHandler).then(completeHandler, errorHandler);
setTimeout(() => sub.cancel(), 1000);
await sub;
```

**Comment by RangerMauve** [comment]
Wouldn't relying on Cancellable Promises mean that this spec would have to wait for them to be accepted first? As far as I can see, Observable is further along to being useable and is a lot more active. I don't think it's a good idea to add the dependency if it'll slow down progress.

Also I personally just disagree with cancellable promises in general.

As for having the overloaded subscribe, I'm still very much in favor of this, but it looks like it's already been decided not to go that route.

**Comment by ljharb** [comment]
The current direction for Cancellable Promises seems to indicate that it'd be trivial for `Observable` to hook into that behavior, and also trivial for users to intercept that behavior via `await`. I do not think that `Observable` needs to be concerned with the semantics of cancellation in Promises in order to eventually work with it - that's for `await` and `Promise` to worry about.

**Comment by blesh** [comment]
> Wouldn't relying on Cancellable Promises mean that this spec would have to wait for them to be accepted first?

No, it just means the returned subscription object would duck-type as a cancellable promise (if cancellable promise happened to match the API).

**Comment by blesh** [comment]
... in other words, it's a "thennable" with a `cancel()` function. Not really related to Cancellable Promise.

**Comment by ljharb** [comment]
s/thennable/thenable :-)

**Comment by RangerMauve** [comment]
Would this mean that the spec would be introducing the concept of promise chains that can potentially never resolve or reject?

Would it maybe make sense to have the promise reject on cancellation? I think that would be a lot less controversial.

**Comment by ljharb** [comment]
@RangerMauve that already exists: `new Promise(() => {})`.

**Comment by RangerMauve** [comment]
@ljharb Is this something that's used in any other APIs? So far I've only seen promise chains that never get resolved or rejected when there were bugs in the code.

**Comment by blesh** [comment]
> Would this mean that the spec would be introducing the concept of promise chains that can potentially never resolve or reject?

The spec is already introducing that, technically... `Observable.never().forEach()` would return such a promise. (`never()` is the same as `new Observable(() => {})`)

**Comment by ljharb** [comment]
"it's not commonly used" doesn't mean it's a new concept ¯\_(ツ)_/¯

**Comment by RangerMauve** [comment]
@ljharb I totally concede that I was wrong in it being a new concept. But I'm asking if it's actually used in real world scenarios. I'm especially skeptical that anything else in the browser uses a pattern like this. I think it's a bad idea to just make things up rather than following common practices.

**Comment by ljharb** [comment]
@RangerMauve perhaps not intentionally, but certainly if you have a promise that stands in for a future value, there may be a scenario where you don't ever have a value.

**Comment by blesh** [comment]
> But I'm asking if it's actually used in real world scenarios. 

Never observables are used in operations where you're switching between observables but don't want the resulting observable to end just yet. Observables like `empty` and `never` are mathematical constants of a sort when it comes to the "math" of observable combinators.

**Comment by blesh** [comment]
Also, with an observable, you could set up an observable that could theoretically stay connected forever and never receive anything. Like a socket connection that never gets any data over it.

**Comment by RangerMauve** [comment]
@blesh I think that's pretty reasonable. Only comment I'd have left is that it should be a subclass of promise rather than just being thennable. By that I mean it should probably have a `.catch()` as well as `.then()`

**Comment by benjamingr** [comment]
If we call it dispose and not cancel, then we can call it "disposable subscription that happens to be a promise subclass" and can probably avoid the bikeshedding.

+1 for the result of forEach being cancellable. +1 for not tying it to promise cancellation.

**Comment by zenparsing** [comment]
@blesh @benjamingr I don't think the semantics are coherent when mixing promise result propagation with observer callbacks.

Again, what happens in the case I mentioned above?

```js
let p = observable.subscribe({
    next(v) {
        throw new Error("boom");
    }
});
```

Is the "boom" error sent to `window.onerror`, or is it stored as the rejection of `p`?  Neither answer seems acceptable.

**Comment by zenparsing** [comment]
> +1 for the result of forEach being cancellable. +1 for not tying it to promise cancellation.

I don't see how those two +1's can be compatible.  : )

I think whatever solution is arrived at for async task cancelation in JS should be applied to `forEach`.  I don't think we should attempt to solve that problem here.

**Comment by blesh** [comment]
> I don't think we should attempt to solve that problem here.

I don't think we have to. The problem we're solving is tangential to promise cancellation. We have a subscription cancellation, and we have a promise. It just so happens that canceling the subscription will also mean the promise never resolves or rejects.

**Comment by benjamingr** [comment]
> I don't see how those two +1's can be compatible. : )

Call it dispose and not cancel. That way we're typing it to "promise disposal" which is something no one ever talked about or ever plans to do anyway :D 

```js
let p = observable.subscribe({
    next(v) {
        throw new Error("boom");
    }
});
```

That's an interesting case because an advantage of observables over promises* is how you have a distinct "end" to the chain. This lets us deterministically figure out when a chain ends. Promises don't have that because they're strict**.

So I tend to agree with you about that. Dart does `toFuture` here. 


What if `subscribe(...)` returns a subscription with `dispose()` and `toPromise()`. If `toPromise` is called within a turn of the event loop (a task) `onerror` isn't called - if it's not then it is. Although that's practically unhandled rejection detection anyway. It's not bad, it catches 99.9% of cases, but we _are_ losing something here (the ability to _know_ when a subscription failed with an error even in weird cases).

I'm starting to feel like observables need to be `await`able but not promises after all in some way. I'll have to think about it some more. Alternatively, we _might_ be OK with something like:

```js
var subscription = obs.subscribe(...);
setTimeout(_ => {
    subscription.catch(...);
}, 1e5);
```

Reporting the error to window.onerror anyway. @domenic might be able to weigh in here.


* (and also necessary because of the inherent non-strictness while constructing the observable so you won't miss events) 
**  (async iterators also have that non-strict property and to a much greater degree (they're a lot less strict than observables), one can always in theory attach a handler)

**Comment by AgentME** [comment]
Subscriptions made by `.forEach` have different semantics from the very start than subscriptions made by `.subscribe`. `.forEach` subscriptions catch and reject with errors and always returns a promise, and the barer `.subscribe` subscriptions have no async or error-catching wrappers and let you completely unsubscribe in a way that all of your callbacks are immediately dropped and never heard from again. Attempting to hybridize them or make it auto-switch semantics while the subscription is active seems like a large possible source of complexity and surprise.

Is this idea about simplifying things, or about trying to justify the existence of a subscription object? The hacks proposed here like nonstandard cancelable promises and auto-switching modes depending on later method calls doesn't sound like it's making things any simpler.

**Comment by blesh** [comment]
This was purely a "shower thought". Nothing more. However, I will admit if I can get this spec to not even have a `subscribe` function, it will prevent me from having to gimp the unsubscription model of my library to match this spec.

**Comment by RangerMauve** [comment]
@blesh Can't you just make it so that Rx observables have whatever semantics they want, but then support returning native Observables via their Symbol.observable method?

**Comment by blesh** [comment]
@RangerMauve Sure. But it was one of the goals of the library to try to match this spec. I think that returning a cancellation function is really a deal breaker for that though, because it's not the right thing to do, and it would incur a lot of hacking in the lib.
