### ISSUE TITLE
WHATWG Streams

### ISSUE THREAD

**Issue by christyharagan** [zenparsing/es-observable#63]
Hey,

Apologises if this has already been asked (and answered), although I couldn't find any reference if so.

How does this spec interop with the [WHATWG Streams spec](https://streams.spec.whatwg.org)? It seems, both solve the same problem, and are potentially conflicting/overlapping specs.

Perhaps the streams spec is broader in scope, but would it then make sense for it to adopt the Observable API?

**Comment by domenic** [comment]
https://github.com/whatwg/streams/blob/master/FAQ.md#how-do-readable-streams-relate-to-observables-or-eventtarget

**Comment by RangerMauve** [comment]
As I understand, WHATWG Streams are more suited for streams of bytes like files or network connections.

**Comment by domenic** [comment]
@RangerMauve https://github.com/whatwg/streams/blob/master/FAQ.md#are-streams-only-for-binary-data

**Comment by RangerMauve** [comment]
@domenic Good to know, thanks.

**Comment by blesh** [comment]
They probably shouldn't be used for anything other than I/O that requires chunking through data and/or back pressure support.

**Comment by benjamingr** [comment]
@blesh why? WHATWG streams are async iterators, while WHATWG streams are a specific case - async iterators are very applicable to a variety of cases.

**Comment by RangerMauve** [comment]
@benjamingr Are streams not more heavy than the ideal observable implementation?

**Comment by benjamingr** [comment]
@RangerMauve of course they are, streams also do a lot more. A good comparison is between observables to async iterators - not with streams.

**Comment by christyharagan** [comment]
Thanks guys. That clarified things :)

Happy to close this if you're after cleanliness. I see the streams spec page *does* have a quick discussion on the differences, so it is documented. But I wonder if there's any value in adding a few lines here too? Maybe, maybe not..

Let me know what to do.

**Comment by christyharagan** [comment]
Ok, before I close, here's my attempt at trying to disseminate the various patterns:

At the most basic level, we have observables and async-iterators (with streams being a special case). 

One way to think about the differences is via their synchronous equivalents:

* For observables, its synchronous equivalent is a function: Given some parameters, perform a calculation and return a result
* For async-iterators, its synchronous equivalent is an iterator: A sequence of values.
* For streams, its synchronous equivalent is an array: A contiguous iterator.

Subsequently, observables as a great way of breaking up computation and composing it asynchronously. Async iterators are a great way of traversing data-structures asynchronously. Streams are a great way of traversing (large) arrays of data asynchronously.

Streams have back-pressure built in, although back-pressure can be provided to all patterns (although the WHATWG FAQ says back-pressure is hard in observables, I know the rx implementations provide it).

Am I roughly right? What corrections are there?

**Comment by benjamingr** [comment]
@christyharagan you might want to read https://github.com/kriskowal/gtor

**Comment by blesh** [comment]
@christyharagan pretty close, and this might just be me correcting a typo, but Observables are also sets. So they don't really return "a result", but rather "zero to many" results. Unless by "a result" you meant a set of values.

**Comment by benjamingr** [comment]
The fundamental difference between observables and async iterators is that observables are a strict push stream over zero or more values and async iterators are a lazy pull stream over zero or more values.

You should use observables when you want push semantics and async iterators when you want pull semantics. It's pretty much as simple as that.

**Comment by zenparsing** [comment]
It seems like this question has been answered to some satisfaction, so I'm going to close.  Please re-open if needed.
