### ISSUE TITLE
Need to clarify proposed API surface area

### ISSUE THREAD

**Issue by jhusain** [zenparsing/es-observable#7]
Got complaint that it's difficult to ascertain exactly what APIs are being proposed because of the additional combinators in the library. May make sense to remove everything but the polyfill and put combinators in a separate repo. Otherwise just clearly listing proposed API in README would do: (System.observer, subscribe, forEach, Observable.from).

**Comment by zenparsing** [comment]
Removed the additional combinators.  Will add "from" and Symbol.observer.  I think it should be named Symbol.observe though, since we are providing the observer.  What was the reason you changed to "observer"?

**Comment by jhusain** [comment]
Similarity to Object.observe makes the name somewhat problematic. It's also why I went with subscribe. I could go either way here, but I recall some on the committee expressing concerns about observe from a naming conflict perspective. Makes sense to me frankly.
