### ISSUE TITLE
Terminology mismatch: closed vs. complete

### ISSUE THREAD

**Issue by domenic** [zenparsing/es-observable#71]
Should be either closed and close(), or completed and complete(), right?

**Comment by zenparsing** [comment]
Well, `completed` might imply that it finished without error, whereas it could finish with an error or it could have been canceled via `unsubscribe()`.

I think the same information is presented in RxJS as `isUnsubscribed()`, a method on the subscription object.

I don't have a strong preference on the name, but none of the above seem like an obvious winner.  I guess the options are:

- unsubscribed
- isUnsubscribed()
- closed
- completed

Any opinions?

**Comment by domenic** [comment]
Oh, this is confusing. So the boolean is meant to be true in which of the following scenarios?

- Canceled via unsubscribe
- Errored via error(e)
- Completed via complete(v)

Maybe a `.state` would be clearer? It could be either "pending", "canceled", "errored", or "completed"?

**Comment by zenparsing** [comment]
Actually, in RxJS it's `isUnsubscribed`, an accessor property.

It's meant to be true in any of those scenarios, basically indicating that the "channel" is no longer active, or capable of receiving anything.  It's typically used by the data source to stop doing some processing early, for instance in Observable.from.

https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L387

One option would be to remove it from the spec for now, since you can get that information by doing something like:

```js
new Observable(sink => {
    let closed = false;
    return _=> {
        closed = true;
    };
});
```

**Comment by blesh** [comment]
For some reason I thought it was `isUnsubscribed` in this spec as well. I can see how that might be confusing if people thought that it meant the consumer initiated shut down.

I'm not sure I like `closed`, myself. There are a lot of terms we could use here though: `terminated`, `disposed`, `stopped`, `unusable`, `finalized`, `done`, etc.

> Maybe a .state would be clearer? It could be either "pending", "canceled", "errored", or "completed"

I'm not so sure. There's really only two states an observer can be in that have any use:

1. It can accept values
2. It can no longer accept values

Granted, number 2 can be reached in 3 different ways, but there aren't any use cases for knowing why it's no longer usable that I can imagine.

**Comment by blesh** [comment]
Perhaps the real option here is to go in the affirmative with the name... like `open` instead of closed. It might eliminate the confusion. Because that's what you want to know, whether or not you can give it more values.

**Comment by Frikki** [comment]
## Rational Formats

### Accessor/Mutator Methods

- If the property is expressed as a noun:
  - (*type*)*noun*;
  - (void)set*Noun*: (*type*)*aNoun*;

  For example:
  ```js
  - (String)title;
  - (void)setTitle:(String)aTitle
  ```

- If the property is expressed as an adjective:
  - (Boolean)is*Adjective*;
  - (void)set*Adjective*:(Boolean)flag;

  For example:
  ```js
  - (Boolean)isUnusable;
  - (void)setUnusable:(Boolean)flag
  ```

- If the property is expressed as a verb:
  - (Boolean)*verbObject*;
  - (void)set*VerbObject*:(Boolean)flag;

  For example:
  ```js
  - (Boolean)readsStream;
  - (void)setReadsStream:(Boolean)flag
  ```
  
  The verb should be in simple present tense.

- Don’t twist a verb into an adjective by using a participle:

  | Example | Correct? |
  | ------------ | ----------- |
  | `(void)setAcceptsSubscribers:(Boolean)flag` | Right. |
  | `(Boolean)acceptsSubscribers` | Right. |
  | `(void)setSubscribersAccepted:(Boolean)flag` | Wrong. |
  | `(Boolean)subscribersAccepted` | Wrong. |

- May use modal verbs (verbs preceded by “can”, “should”, “will”, and so on) to clarify meaning, but don’t use “do” or “does”.

  | Example | Correct? |
  | ------------ | ----------- |
  | `(void)setCanSubscribe:(Boolean)flag` | Right. |
  | `(Boolean)canSubscribe` | Right. |
  | `(void)setShouldCloseStream:(Boolean)flag` | Right. |
  | `(Boolean)shouldCloseStream` | Right. |
  | `(void)setDoesAcceptSubscribers:(Boolean)flag` | Wrong. |
  | `(Boolean)doesAcceptSubscribers` | Wrong. |

- Use “get” only for methods that return objects and values indirectly. Use this form for methods only when multiple items need to be returned.

**Comment by blesh** [comment]
... scratch my idea with looking for something in the "affirmative" (`isOpen`, for example)... Anonymous Observers (object literals some mix of `next`, `error`, and `complete` handlers on it) won't have a property defined for that... so it will mean we need to check something that is false or "falsey" by default.

**Comment by zenparsing** [comment]
@blesh Ah, good point.  Right now, I'm leaning toward removing it from the spec in the spirit of minimalism.  Any objections?

**Comment by blesh** [comment]
@zenparsing I guess the thing is there's really two types of Obsevers: 

1. Anonymous Observers, that are just objects with some mix of 0 to 4 handlers on them, that *don't* need `isUnsubscribed`.
2. "Safe" Observers, that have all handlers implemented and have guarantees about not being able to next after the subscription is done, and *do* care about having an `isUnsubscribe` property for use in synchronous unsubscribe situations.

**Comment by blesh** [comment]
:+1:  makes sense.

**Comment by domenic** [comment]
I still think significant bikeshedding is necessary for the name. If the semantics are that all three of https://github.com/zenparsing/es-observable/issues/71#issuecomment-156489627 should give true, then both isUnsubscribed and closed seem massively wrong. Maybe borrowing "settled" from promises? Meh.

**Comment by blesh** [comment]
I'm fine with `settled`, honestly.

**Comment by zenparsing** [comment]
I'm backing this property out of the core proposal for now.  It's not essential to any of the proposed methods, and sometimes a hard bikeshedding problem means that something needs to be cut.

Without this property, we do have the issue that the subscriber function can't tell whether the subscription is cancelled until after the subscriber function returns.

```js
new Observable(sink => {
    let done = false;
    sink.next(1);
    // At this point the subscription is cancelled, but we don't know it yet
    assert(done === false);
    return { done = true };
}).subscribe({
    start(s) { this.subscription = s; },
    next(x) { this.subscription.unsubscribe(); },
});
```

I would also like to remove `start` from this proposal as well.

**Comment by blesh** [comment]
> I would also like to remove start from this proposal as well

:+1:
