### ISSUE TITLE
forEach should probably take a second thisArg parameter

### ISSUE THREAD

**Issue by domenic** [zenparsing/es-observable#72]
Just for consistency with the sync version and with potential expectations. Nobody thinks it's a very good idea for any other reason, but at TC39 this came up and the consistency argument seems to win. Seems like an easy fix.

**Comment by benjamingr** [comment]
What about throwing on people accidentally passing a second argument as an alternative "fix"?

Not sure which is better.

**Comment by RangerMauve** [comment]
I think that consistency with `forEach` in other primitives is definitely better than throwing or just being inconsistent.

**Comment by zloirock** [comment]
#8

**Comment by blesh** [comment]
FWIW: We're talking about removing `thisArg`s from various operators in RxJS 5. Just seems unnecessary.

**Comment by zenparsing** [comment]
Fixed
