### ISSUE TITLE
proposal: Observable implement Iterable interface

### ISSUE THREAD

**Issue by dfahlander** [zenparsing/es-observable#73]
Proposal:

Observable.prototype[Symbol.iterator] = *function returning an Iterator delivering Promise values*

If Observable returned an iterator from Observable[Symbol.iterator], delivering Promises to await, one could always do the following:

```js

for (const promise of observable) {
    const nextValue = await promise;
    if (wantToUnsubscribe)
        break; // will call Iterator.return(); --> unsubscribe internally.
}

```

Iterator interface (as specified in [ecma-262](http://www.ecma-international.org/ecma-262/6.0/#sec-common-iteration-interfaces))

```ts
interface Iterator {
    next() : IteratorResult<Promise>; // call subscribe() internally on initial call()
    throw(); // Not used.
    return(result); // call subscription.unsubscribe() internally.
}

interface IteratorResult<T> {
    value: T;
    done: boolean;
}
```

* Initial call to Iterator.next() would call observable.subscribe() internally
* Calling Iterator.return() would call subscription.unsubscribe() internally, making it possible to unsubscribe using a *break;* statement in the *for..of* loop.

Upon first call to next(), subscribe() would be called internally.

### Sample from README
```js
let subscription = commandKeys(inputElement).subscribe({
    next(val) { console.log("Received key command: " + val) },
    error(err) { console.log("Received an error: " + err) },
    complete() { console.log("Stream complete") },
});
```
### Equivalent using async function with a for..of loop:
```js
try {
    for (const promise of commandKeys(inputElement)) {
        console.log("Received key command: " + await promise);
    }
    console.log("Stream complete");
} catch (err) {
    console.log("Received an error: " + err);
}

```

**Comment by dfahlander** [comment]
The idea was inspired by https://github.com/Reactive-Extensions/RxJS/issues/1045

**Comment by benjamingr** [comment]
@dfahlander uhh, you're aware of the async iterators proposal right?

**Comment by RangerMauve** [comment]
Yeah, with Observables it might make more sense to make them [async-iterators](https://github.com/zenparsing/async-iteration) since they might not complete synchronously.

**Comment by dfahlander** [comment]
True that async-iterators makes even more sense. I had read about them but forgot about it.

Would be nice though if Observable implemented the AsyncIterator interface which is not within the current proposal as I could see.

**Comment by RangerMauve** [comment]
From what I'm seeing, Observables seem to have more buzz around them than async-iterators, so I'd imagine that they would get accepted much sooner. Maybe it would make sense to add the async-iterator stuff to Observable when async-iterators are closer to being accepted.

**Comment by benjamingr** [comment]
Yeah, let's make it clear:

 - Interop converting a push stream to a pull stream is problematic - namely there are issues of backpressure that need to be handled and it introduces unbounded buffers. An observable interface wouldn't signal "ready" to more requests by calling `.next` internally - so it would need to aggregate all the incoming requests somewhere. This isn't a simple issue. 
 - We shouldn't add drastic changes to this proposal this late - you can already use `.forEach` for async/await which works fine. a `for... on` loop is (might be?) planned too.

**Comment by blesh** [comment]
@benjamingr hit the nail on the head with backpressure concerns. Async iterators and/or IoP are different animals with different use cases. This could be implemented as an extension, of course. But probably shouldn't be core, IMO.

**Comment by zenparsing** [comment]
Thanks all, for the responses.  It's certainly possible that, given async iterators (which we are planning on advancing) we could add a `Symbol.asyncIterator` method to `Observable.prototype`, and thereby allow them to be consumed directly by `for await` loops.  That would be nice.

As @benjamingr and @blesh previously stated, though, there's the issue of backpressure policy.  One policy would be to have an unbounded queue.  Another policy would be to drop "events" that occur before the consumer is ready for them.  The choice of policy seems to depend on the circumstances, so it's not clear what the correct default should be.  Another option would be to transmit the backpressure information to the source observable via a promise-typed return value from the observer used in the `Symbol.asyncIterator` method.

In any case, we want to work on these two proposals independently for now.

**Comment by eggers** [comment]
+1

I was working on some helper functions for implementing the async-generator proposal within the current spec. I've also just added a `wrapObservable` helper that would wrap an observable and dispose of it when done.

See: [eggers/async-generator@wrapObservable](https://github.com/eggers/async-generator/tree/wrapObservable)

**Comment by zenparsing** [comment]
Going to close this since it's on our radar, but we don't want co-dependencies between proposals yet.  Thanks for bringing this up though!
