### ISSUE TITLE
Implementation doesn't match spec

### ISSUE THREAD

**Issue by hollowdoor** [zenparsing/es-observable#76]
There is this statement in this spec: **Note: The "filter" and "map" methods are not included in this proposal. They may be added in a future version of this specification.**

Over here https://github.com/zenparsing/zen-observable there are filter, and map methods. I'm not sure if the zen-observable is supposed to be exactly like the spec, or if those methods are just experimental.

**Comment by zenparsing** [comment]
@hollowdoor They are experimental

**Comment by hollowdoor** [comment]
Now I'm curious. What do you think of them? Do you think they should be allowed in the spec?

Most observing libs have almost as much, or more methods than array. As with array I guess that could be argued about later. There are methods still being added to the javascript array this year.

I know there's an issue somewhere already asking for filter, and map. I'll close this one soon. I just wanted your opinion. Maybe it's changed. :)

**Comment by zenparsing** [comment]
@hollowdoor I like them : )  The starting goal here was a minimal specification, so we left them out for now.

**Comment by hollowdoor** [comment]
@zenparsing If this spec is accepted will you leave the zen-observable repo to be used as a polyfill? Sorry for a bunch of unrelated questions. Figured I'd get it out of my system. I've been messing around with the zen-observable module lately. I'd like to see it in the standard.

**Comment by zloirock** [comment]
@zenparsing 
> I like them : )

With `.filter` and `.map` methods, `Observable` much more useful than without - it's like `Promise` without `.all` and `.race`. Maybe makes sense add it at once?

**Comment by benjamingr** [comment]
The only really important method for observables is flatMap, I have a feeling you can build the rest very easily on top of that. That said - the idea is to have es-observable in the spec as a standard cross-library interface and have libraries align to that so you can expose observables people can easily consume - like promises.

Promises made similar sacrifices - giving up on `.finally` and similar things.

By the way, `.race` is a terrible primitive for promises :)

**Comment by zloirock** [comment]
How many people who use native `Promise` write own combinators? Available combinators enough for a comfortable work. I don't think the situation with current minimal `Observable` proposal is the same.

**Comment by benjamingr** [comment]
> How many people who use native Promise write own combinators?

Probably less than 100, but a  big portion of the rest use libraries that provide advanced combinator functionality. Kind of like what I anticipate will be with es-observable, with large parts of the community using libraries like rx.

**Comment by zloirock** [comment]
A big portion, but not most. With current minimal `Observable` most people should do it. I don't think it's a good conception.

**Comment by ljharb** [comment]
One of the appeals of native Promises is *not* having to use a library, and many eschew libraries despite missing out on convenience methods. The same will be true of a native `Observable`.

It would be ideal to include some basic combinators rather than expecting people to build and use libs.

**Comment by hollowdoor** [comment]
@zloirock @ljharb This is funny. :) For this proposal I think minimal is fine. The reason I'm interested is because I'm actually attempting to make an experimental library based on this spec. All of the combinators, and other stuff are my own. The zen-observable even has filter, and map, but I re-did those myself.

But observables are like arrays, and arrays have all you could ever want so the jury is still out for simplicity vs. everything inside, or somewhere between. In the end every lib might change any methods that come with the spec because they all have opinions on how those should work.

For instance the scan method.

**baconjs** `observable.scan(seed, callback)`

**rx** `observable.scan(callback, seed)`

Even then a native scan would not be so bad. For inheritance just switching arguments is easy.

I'll be closing this soon just so you all know. This simple issue has been resolved. I'm leaving it for a little bit so others can see @zenparsing 's answer easily. Unless he closes it.

**Comment by hollowdoor** [comment]
This has been open long enough.

**Comment by zloirock** [comment]
@zenparsing your opinion about the discussion above?

**Comment by zenparsing** [comment]
@zloirock I don't think we can add filter and map back to this spec right now, based on the previous discussions.  On the other hand, I don't think we have a complete API without them.  For the time being, I would strongly suggest that all observable libraries, if they implement "filter" and "map", implement them with a signature that is consistent with the array methods.

**Comment by hollowdoor** [comment]
+1 for consistency with array methods.
