### ISSUE TITLE
Remove thisArg from forEach

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#79]
I've removed the `thisArg` parameter from `forEach`.  Two reasons:

1. I think consistency with Array in this case is a poor reason to visit this vestigial callback pattern on future ES built-ins.
1. For future-proofing, we should leave open the second argument for a cancellation token.  I would prefer if we could find a better, more ergonomic way to manage cancellation, but we should leave our options open for now.

@blesh What do you think?

**Comment by benjamingr** [comment]
Isn't cancellation managed through the subscription mechanism?

As for `thisArg`, the argument for it was similarity with `Array#forEach`. Personally I don't think this is a big deal. Arrays are not like observables anyway - iterators are and those don't have `forEach`.

`Set`s also take a `thisArg` in their forEach and so do `Map`s.

**Comment by zenparsing** [comment]
@benjamingr Right, but when you invoke `forEach` you don't get a subscription back, you get a promise.  You're treating the subscription as an async operation, basically.

**Comment by benjamingr** [comment]
Oh, I assumed if you wanted to cancel you wouldn't use `forEach`. 

We had the whole discussion of whether or not subscribe would return a `thenable` or not (and on the flip side if `forEach` would return a promise with a `.dispose` method . IIRC neither were done. 

Did we ever consider passing the subscription as a second argument for the `forEach` callback? Was that ruled out?

**Comment by zenparsing** [comment]
> We had the whole discussion of whether or not subscribe would return a thenable or not (and on the flip side if forEach would return a promise with a .dispose method

Right, both of those are verboten.  : )

> Did we ever consider passing the subscription as a second argument for the forEach callback? Was that ruled out?

I don't think so.  We discussed the possibility of the observer's "next" handler getting a subscription object as the second parameter.  If we had gone with that, we could have then passed the subscription on to the `forEach` callback.  As it is, `forEach` doesn't get a subscription until after "subscribe" has completed, which could be after data is sent.  (Ah, synchronous dispatch!)

I think the only future proof thing to do in this case is just to drop the `thisArg`.

**Comment by ljharb** [comment]
This sounds like something that would need committee consensus :-/

**Comment by zenparsing** [comment]
Well the whole thing needs committee consensus, doesn't it?

**Comment by ljharb** [comment]
lol true, i just mean, i suspect there will be a lot of discussion around *not* including the `thisArg`, whereas I doubt there would be much of any discussion around *including* it.

**Comment by blesh** [comment]
It seems reasonable. I actually hate `thisArg`, and now that `.bind()` speed has improved so much in Chrome and FF, I'm not sure I care about `thisArgs` at all, because I think using `.bind()` is more readable.

**Comment by zenparsing** [comment]
@ljharb I think you're probably right, and if it came to that I don't mind adding the `thisArg` too much.

But for now, I'm going to close this issue.
