### ISSUE TITLE
Reference Impl: `forEach` unsubscription on sync value

### ISSUE THREAD

**Issue by blesh** [zenparsing/es-observable#80]
As discussed here https://github.com/ReactiveX/RxJS/issues/1411#issuecomment-193530811

Basically the issue is if you have a _synchronous_ observable, and you call `forEach` on it with a handler that throws, it's not going to call the teardown logic, and will, in fact, error because `subscription` [doesn't exist here](https://github.com/zenparsing/es-observable/blob/c22dd71a3349df30ac8f4e99c1b98008f54f232c/src/Observable.js#L298)

Code to reproduce should be as simple as this:

```js
const source = new Observable((observer) => {
  observer.next('test');

  return () => {
    console.log('call me');
  };
});

source.forEach(() => {
  throw new Error('bad');
});
```

**Comment by blesh** [comment]
If it helps, the proposed fix for RxJS 5 is in this PR: https://github.com/ReactiveX/RxJS/pull/1434

**Comment by zenparsing** [comment]
Agreed, and I think that this is another illustration of why synchronous emission is a footgun.

**Comment by zenparsing** [comment]
Why do we need to allow the possibility of synchronous emission?

**Comment by blesh** [comment]
For one thing: DOM Events can be synchronously triggered after registration.

**Comment by zenparsing** [comment]
Definitely, but they will never emit before `subscribe` has returned.  In my view, sending data before the subscription object has been returned is really a protocol-handshake violation.  Not sure if there's anything that can be done to help the situation though...

**Comment by zenparsing** [comment]
In this case though, I think it's arguable that perhaps the cleanup function should not get called and the stack should be unwound at the point where the observer called "next".

**Comment by zenparsing** [comment]
This is essentially the same case as #81.  If an observable calls "next" synchronously, and the observer throws, then we shouldn't protect the observer in that scenario.  It should just unwind the stack as usual.  The moral of the story is:  don't emit before you return your cleanup function.

**Comment by trxcllnt** [comment]
@zenparsing both BehaviorSubject and ReplaySubject synchronously next (or error/complete) before the call to `subscribe` returns. This isn't a problem in pure functional code, only code with shared mutable state.

**Comment by zenparsing** [comment]
@trxcllnt Thanks for the pointers to BehaviorSubject and ReplaySubject.  I think that there may be better ways to represent such abstractions without using synchronous emission.  More on that after I try some experiments.

Synchronous emission is (in my view) a serious problem for the API from a standardization point of view.  Adding a "subscription" argument to "next" (#84) is just a patch over the real problem.

**Comment by trxcllnt** [comment]
@zenparsing I understand the argument against synchronous emission at the standards level (even if I disagree), but would like to highlight the danger of _forced_ asynchronous emission with no escape hatch. You simply can't write `groupBy` (the inverse of `flatMap`) without at least the possibility of synchronous emission. Perhaps a sister Scheduler standard is necessary?

From my experience, sync vs. async emission is something engineers struggle with the first 10-20% of their time using Observables, but don't have trouble with the other 80%, at which point they're experienced enough to take advantage of the composability of the API in their architecture, but still reap the performance benefits of synchronous emission. I've heard of Promise implementations (Q maybe?) that attempt to execute synchronously if possible, which if true, would seem to support this argument.

While I would be disappointed with asynchronous emission specified as the default, I wouldn't argue against the proposal if there were a way to replace the mechanism that controls the time dimension (which is all Schedulers do). Emitting synchronously through a Scheduler isn't the fastest (emitting via loops is), so it seems silly to hurt synchronous performance if it's something people learn and move beyond relatively quickly.

**Comment by blesh** [comment]
I mostly agree with @trxcllnt... 

**Observables are just types of functions.** Are we going to force all callbacks passed to functions to be async? They model DOM events. They model functions with callbacks. They model looping over arrays.

force async takes Observable from "another flavor of a function" territory into something more a little more complicated. There are some disadvantages too, where before you could use a synchronous observable as an input to an API that accepts an observable for something like server-side rendering of Angular 2 or React or something, and now you're scheduling on the next tick.

Another issue is scheduling always negatively impacts debugging. I don't really like the argument that "it's a problem for tooling", that's just hand-waving.

**Comment by blesh** [comment]
Effectively, I'm asserting that Observables are too primitive for this type of concern. They're not Promises, they're a specialized function more than anything.

**Comment by zenparsing** [comment]
Closing since `forEach` is gone : )
