### ISSUE TITLE
Immediately invoked `next` (or similar) prevents unsubscribing

### ISSUE THREAD

**Issue by Alxandr** [zenparsing/es-observable#83]
So, I've made the following sub-class of `Observable` using `zen-observable`:

```js
class Property extends Observable {
  constructor(initialValue) {
    super(s => {
      this._subs.push(s);
      s.next(this._value);
      return () => this._subs = this._subs.filter(sub => sub !== s);
    });
    this._value = initialValue;
    this._subs = [];
  }

  update(newValue) {
    this._value = newValue;
    this._subs.forEach(s => s.next(newValue));
  }
}
```

What this does is basically keep track of a "current value", and immediately emit that on new subscriptions. I use it as a state-container. For most use-cases this has been working great, however, in testing I've discovered the following problem:

```js
const sut = new Property(0);
const sub = sut.subscribe({
  next(value) {
    expect(value).to.equal(0);
    sub.unsubscribe(); // <- this here crashes because `sub` is undefined.
  }
});
```

I've gotten around this problem by delaying execution of `s.next()` (by doing `Promise.resolve(null).then(() => s.next(value))` cause that should in theory make it a microtask), but this feels sort of dirty to do manually, and I feel this should be handled by the `Observable` itself. Is this a scenario that will not be supported?

**Comment by benjamingr** [comment]
We've discussed this before and considered passing the subscription as a second parameter to `next`. Also see https://github.com/zenparsing/es-observable/issues/81

**Comment by Alxandr** [comment]
Passing the subscription as a parameter to next here would not help me, neither would handling unsubscribe. For this scenario to work intuitively (at least as I see it), `next` calls needs to be scheduled, not executed directly, so that the subscription can be returned before the call is invoked. Coming from promises, this is also what I'd expect from an observable.

**Comment by Alxandr** [comment]
Also, another issue this gives me is the following code:

```js
const sut = new Property(0);
sut.subscribe({
  next(value) {
    console.log(value);
  }
});
sut.update(1);
```

If I delay the `next` call in the `subscribe` callback, without delaying the one from `update`, I get the values in the wrong order (worse yet, I get an outdated value last). Therefore I have to manually delay in both places to make sure the order is correct.

**Comment by blesh** [comment]
So the solution for this is as simple as using your own subscription object.

```js
const sut = new Property(0);
const sub = new Subscription();

sub.add(sut.subscribe({
  next(value) {
    expect(value).to.equal(0);
    sub.unsubscribe(); // <- this here crashes because `sub` is undefined.
  }
}));
```

Unfortunately, this spec doesn't contain anything for chaining Subscriptions together, IFAIK.

But a Subscription class that could handle this is pretty simple, some pseudo-code:

```js
class Subscription {
  constructor(_unsubscribe) {
    this.isUnsubscribed = false;
    this.innerSubs = [];
    this._unsubscribe = _unsubscribe;
  }
  
  add(subscription) {
    if (this.isUnsubscribed) {
       subscription.unsubscribe();
    }
   this.innerSubs.push(subscription);
  }

  unsubscribe() {
    this.isUnsubscribed = true;
    while(this.innerSubs.length > 0) {
       this.innerSubs.shift().unsubscribe();
    }
    if (this._unsubscribe) {
        this._unsubscribe();
    }
  }
}
```

You could add a `remove()` function to that as well, if you choose. This is a _very_ basic version of the shape of Rx's Subscription.


In theory this should work, because I believe (or at least I hope) that this spec's Observer implementation is checking `isUnsubscribed` on itself before allowing any emissions.

**Comment by blesh** [comment]
Looking at it, you could probably decorate and patch the zen-observable's Subscription object to support this.

```js
const origUnsubscribe = Subscription.prototype.unsubscribe;
Subscription.prototype.unsubscribe = () => {
  this.isUnsubscribed = true;
  const innerSubs = this.innerSubs;
  if (innerSubs) {
    while(innerSubs.length > 0) {
       innerSubs.shift().unsubscribe();
    }
  }
  origUnsubscribe();
};

Subscription.prototype.add = (sub) => {
  if (this.isUnsubscribed) { sub.unsubscribe(); return; }
  this.innerSubs = this.innerSubs || [];
  this.innerSubs.push(sub);
};
```

**Comment by blesh** [comment]
The argument has been made so many times that emitting values from Observable should be done asynchronously, or that subscription should be asynchronous, and it's failed every time. For a variety of reasons. I've even made this argument a few times. If you search through the closed issues you'll find all of the discussions around this.

**Comment by zenparsing** [comment]
@Alxandr A hard requirement for the observable design is that next values should not be queued.  Consider the case where we are observing an infinite iterator. 

Thanks for bringing up this issue though.  I'm becoming convinced that we ought to add the subscription as a second parameter to next to deal with these synchronous use cases. 

Thoughts?

**Comment by zenparsing** [comment]
@Alxandr Although I think your use case is confusing synchronous state with asynchronous state changes. Can you not poll the property for the synchronous state instead?

**Comment by Alxandr** [comment]
@zenparsing I cannot poll values from the property (if I'm reading your comment right), because I have no idea when the values will change. The only difference between a regular `Observable` and a `Property` is that a property maintains the last emitted value as a "current" value, and always immediately emits it on new subscribtions. I've yet to make it, but once I'm done you'll be able to call a `makeProperty(someObservable, initialValue)` too, where it would subscribe to the observable passed in, and return a property which simply keeps track of it's emitted values (you would obviously not be able to call `update` on it at that point, but you should get the point).

As regards to your solution @blesh, as that would certainly work in my use-case, it has the unfortunate effect of pushing the cognitive load of dealing with "I may call next before I return" to the consumer of my API, which is unfortunate. For my tests, it wouldn't matter much, but it'd still be an edge-case where people could (and probably would) end up with bugs.

Also, I have a suggestion as to a potential solution. How about simply using the subscription as the context in `next`, `error` and `completed` calls? So I could do this:

```js
const sut = new Property(0);
sut.subscribe({
  next(value) {
    expect(value).to.equal(0);
    this.unsubscribe(); // next called with this as the subscription
  }
});
```

I think that'd make sense to me at least.

**Comment by Alxandr** [comment]
For now, I made a `safeSubscribe` function that takes a `observerFactory` and I call it like this:

```js
const sut = new Property(0);
sut::safeSubscribe(sub => ({
  next(value) {
    expect(value).to.equal(0);
    sub.unsubscribe();
  }
}));
```

Internally, the function uses the technique by @blesh.

**Comment by blesh** [comment]
FWIW, if you were using RxJS 5, it would be as symbol as returning your observable with `return sut.subscribeOn(Scheduler.asap)`. As `subscribeOn` is an operator that defines when subscription will occur for an observable, and `Scheduler.asap` is the "micro task" scheduler.

RxJS 5 tries to be as compliant with this spec as possible.

**Comment by zenparsing** [comment]
@Alxandr 

> How about simply using the subscription as the context in next, error and completed calls?

The `this` value really must be the observer in this case; it is the object upon which we call the method.  We could provide the subscription as an additional parameter to `next` though.  It would provide the same information.  Would that work for you?

**Comment by Alxandr** [comment]
@blesh Yeah, problem is I'm writing a library, and I try to not decide for the users what implementation of `Observable` they use, as long as it has a `subscribe` function more or less.

@zenparsing Yeah, that'd work. Though, it'd have to be provided to the other callbacks too for the same reasons.

**Comment by blesh** [comment]
> and I try to not decide for the users what implementation of Observable they use, as long as it has a subscribe function more or less.

It sounds like the users are providing the Observable impl, and you're doing the subscription part. Have you looked into using the `[Symbol.observable]()` method to get a "lowercase-o observable"? You could then call `subscribe` on it, and get a `Subscription` object back that you can wrap yourself in a manner similar to what I've outlined above.

**Comment by Alxandr** [comment]
@blesh It seems (which is likely) that there are parts of the specs I've not read/understood, cause I don't know what the difference between a lowercase-o observable and a regular observable is. Also, my library is just expecting there to be a `global.Observable` available at runtime.

My problem is that what I'm technically doing is sort of like `myObservable.first()`, right? Without actually having a `first` method. As long as I was implementing this `first` method on my own, and it would only be used by my library, I'd be OK with the trick of wrapping `Subscriptions` (in fact, that's what I do in my tests atm), but there is a problem in that I can see users of my library wanting to do the same in their code. I could solve this by making my implementation of `first` available to my users, so that they would call it, but my library has little to nothing to do with actually manipulating `Observables`, and it'd be a utility-function that really should not need to be part of my library. I'm sorry if I'm rambling, but I hope you can understand what I'm saying. Basically, I think it's bad that this is a use-case users should have to think about, but unfortunately there's no way around that. Thus, I think it's bad to say to users that you need 4 lines of "bloat" every time you want to "safely" subscribe to a observable.

**Comment by benjamingr** [comment]
@Alxandr write an npm module that does `first` on an arbitrary spec conforming observable, publish it to npm for people to use and then require it in your library.

**Comment by benjamingr** [comment]
The spec is meant to be minimal intentionally - after the proposal makes it into the language more features can be considered.

**Comment by zenparsing** [comment]
It should be almost trivial to implement `first` on top of the minimal API.  Unfortunately, it's currently tricky because of the synchronous case.  Adding a "subscription" argument to next helps.

**Comment by Alxandr** [comment]
Yes. My point was that something as trivial as `first` should be really easy to implement on the "common API". And @benjamingr I agree that it should be really minimal. I don't even use `map` which the `zen-observable` provides. I only expect a single method, `subscribe` in my code.

Also, as I discovered, @zenparsing, an alternative to passing the subscription along with `next`, is doing as I have in my `safeSubscribe` function, and adding an overload of `subscribe` which accepts a `Subcription -> Observer` function instead of simply an observer. In other words, define `subscribe` as the following type:

```js
// Subscribes to the sequence
subscribe(observer: Observer | Subcription -> Observer): Subscription
```

This would allow for the following:

```js
myObs.subscribe(s => ({
  next(v) {
    console.log(v);
    s.unsubscribe();
  }
}));
```

Anyways, both solutions (this and adding the subscription to next) would work. Personally, I think this one is slightly more elegant, but the most important part is that the scenario is actually doable.

**Comment by blesh** [comment]
You know, @zenparsing, ultimately people are going to want a "composite" subscription. basically a Subscription with an `add` and `remove` method on it. That solves this problem and many more and matches the shape of RxJS.

**Comment by zenparsing** [comment]
@Alxandr I think there is a way to implement your "Property" class without having to synchronously notify the observer.  Basically, you can schedule a task to send the current value and cancel that task if the value is updated before the task executes.  Something like this:

```js
class Property extends Observable {
    
    constructor(initialValue) {
        super(observer => {
            this._observers.push(observer);
            this._newObservers.push(observer);
            
            if (this._newObservers.length === 1) {
                // All "new observers" need to recieve the current value no later
                // than the next tick.
                Observable.from(this._newObservers).subscribe({
                    next: observer => { observer.next(this._value) }
                });
            }
            
            return () => this._observers = this._observers.filter(obs => obs !== observer);
        });
        
        this._value = initialValue;
        this._observers = [];
        this._newObservers = [];
    }

    update(newValue) {
        this._value = newValue;
        // New observers no longer need the "next tick" notification, so remove
        // them all from the list.
        this._newObservers.length = 0;
        this._observers.forEach(obs => obs.next(newValue));
    }
    
}

let p = new Property(1);
let s = p.subscribe(observer); // Receives 1 on next tick, unless we update the property before that
```

**Comment by Alxandr** [comment]
@zenparsing that was my first thought too, but I quickly put it away for several reasons. My main problem with this is the inconsistency though. It can lead to subtle, hard to find bugs, because sometimes it's synchronous, and other times it's not.

**Comment by zenparsing** [comment]
Going to close this since we now have the `start` method which allows for synchronous unsubscription.
