### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by johnjbarton** [zenparsing/es-observable#85]
Anyone that works for a corporation can't use any code here (even in gist) w/o a copyright statement and a license.  Thanks!

**Comment by nissoh** [comment]
Hey @johnjbarton. you can use https://github.com/zenparsing/zen-observable based on this repo's spec.

I might just add that i would like to see bare implementation with zero combinators.

**Comment by johnjbarton** [comment]
Thanks!
