### ISSUE TITLE
Make "from" and "of" synchronous

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#88]
Currently, the spec says that `Observable.from` and `Observable.of` schedule a job to emit data.  The rationale for this was as follows:

- Avoiding early (i.e. before `subscribe` returns) emission avoids Zalgo issues.
- Early emission doesn't give the observer a way to unsubscribe, since the subscription object has not been reified yet.

Underlying these points was my general feeling that early emission was an anti-pattern that should be avoided in any case.

Unfortunately, I forgot that early emission is actually fundamental to the protocol because errors that occur during subscription initialization are sent synchronously to the observer.  In the following example, the error is sent to the observer before the call to `subscribe` returns.

```js
new Observable(_=> {
    throw new Error("Oops");
}).subscribe({
    error(err) { console.log("Got an error") }
});
```

Consequently, I now think it is inconsistent to try to force asynchrony in `of` and `from`.  However, I still believe that offering Zalgo protection (and reentrancy protection, for that matter) are important for consumers at the end of the observable chain.

So, the proposal:

- Change `of` and `from` to dispatch immediately, instead of from a job.
- Modify `forEach` so that it makes the following guarantees:
  - The callback provided to `forEach` is never called before the `subscribe` call has returned, queuing if necessary and delivering queued data in a job.
  - The callback provided to `forEach` is never called recursively.  Data is queued if necessary.

This does not address the current deficiency where an observer can't unsubscribe from a synchronously dispatching producer.  I'm fine with that, but it is important to others I can start another discussion for adding a "start" method or similar.

**Comment by blesh** [comment]
So just to clarify:

- `of` no longer schedules
- `from` no longer schedules
- `forEach` will schedule on the next "micro task".

**Comment by zenparsing** [comment]
Right, for `of` and `from`.

For `forEach`, I'm proposing something a little more complex and subtle.  Basically, it only schedules a job under the following scenarios:

- `subscribe` has not returned yet.
- The `forEach` callback is currently executing.
- There are queued notifications because of the first two conditions.

**Comment by blesh** [comment]
> subscribe has not returned yet.
> The forEach callback is currently executing.
> There are queued notifications because of the first two conditions.

Heh... you like to make my life difficult, don't you? :P  (Enter `Rx.Scheduler.zen`) 

@mattpodwysocki what do you think about this form of scheduling? I think it's interesting, but I've never even considered such a thing.

**Comment by blesh** [comment]
also cc/ @trxcllnt, I'd love to read your thoughts on the `forEach` scheduling @zenparsing is proposing.

**Comment by benjamingr** [comment]
In the last few months I've used Rx for more synchronous stuff just for push where my prior experience was mostly using Rx for asynchronous tasks. 

I agree that forcing asynchronicity is kind of silly here - I also agree with @blesh's point from the previous discussion about Zalgo not really being relevant here. I can only attribute my earlier opinion in the last discussion only to my own lack of experience in using Rx like that. 

It seems tempting to think of this as a problem - but with observables scheduling and order of actions is super explicit anyway and unrelated to asynchronisity. That said - I think it would be interesting to observe existing code bases for "Zalgo" to see if _other people_ use Rx in a way where it would create a footgun.  

I'm also fine with `forEach` being completely synchronous as promises would take care of the asynchronisity in async/await for users anyway and it would be impossible to run code synchronously on completion.

**Comment by zenparsing** [comment]
> I'm also fine with forEach being completely synchronous as promises would take care of the asynchronisity in async/await for users anyway and it would be impossible to run code synchronously on completion.

Sure, the complete/error value is taken care of with the completion promise, but there's still the potential issue with early dispatch into the `forEach` callback, and also reentrancy into the callback.

On the other hand, it may be that the more complex scheduling required to work around these problems is worse than the problems themselves.  I'm not sure...  I am concerned about presenting an update to TC39 in which we completely give up on zalgo.

**Comment by zenparsing** [comment]
After more thought, the scheduling I proposed for `forEach` doesn't really make much difference, since other callbacks in a chain leading up to `forEach` are going to get called whenever they are called.

I give up : )

**Comment by benjamingr** [comment]
Ok, so can we agree on synchronous dispatch?

This is the same as event emitters today. Scheduling, like everything else (such what values are pushed) is controlled on the producer side - where it should be.

Pinging @domenic as he was (like me) outspoken against this before, I changed my mind on this so I feel like we should be talking to him about it.

**Comment by zenparsing** [comment]
Done
