### ISSUE TITLE
Add `isUnsubscribed` or similar

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-observable#90]
I think we missed an essential feature by not providing an `isUnsubscribed` or equivalent to the subscription and "SafeObserver" interfaces.  It really is necessary for correctly implementing combinators.

It needs to be a getter, as opposed to a regular data property.  Also, I'm uncomfortable with the name "isUnsubscribed" for a couple of reasons:

- Although the ES standard library does have `is[Adjective]` functions (e.g. `isArray`), those functions take some object as an argument that they are testing.  That naming pattern isn't used for instance methods.  The only boolean getters in the ES standard library are the RegExp.prototype getters like "sticky" and "global", which simply leave off the "is".  For the DOM, the "is" seems to be generally left off (e.g. "checked").
- We are actually concerned with whether the subscription is closed.  It might be closed because of completion, error, or unsubscription.

So:

1. Are there any objections to adding such a getter property on subscriptions?
1. Can we entertain some bikeshedding with regard to the name of the getter property?

**Comment by ljharb** [comment]
Why a getter instead of just a synchronous function?

**Comment by zenparsing** [comment]
> Why a getter instead of just a synchronous function?

In this case we're just exposing some (otherwise) private state of the subscription object; no computation is involved. I think in general the guideline is to express such things with a getter?

**Comment by ljharb** [comment]
I'm not sure there's really a guideline there - certainly Map/Set `size`, and legacy Array/String `length`, use getters, and there's several examples of data properties. However, there's also `Date.now()`, and all the Date getter functions.

Using a getter forces things to use a slower alternative, including polyfills, as well as my personal belief that it's subjectively less ergonomic to use.

**Comment by benjamingr** [comment]
Show us a use case?

**Comment by zenparsing** [comment]
The `map` combinator needs to make sure that the mapping function is not called again if it has previously thrown an error.  We might assume that calling `observer.error` will ensure that the subscription to the source observable is cancelled, but in the synchronous dispatch case *the source observable has not yet given us a subscription to cancel*.  We therefore need a way to tell whether or not the observer is "closed", so that we can short-circuit from within `map`'s "next" handler.

That was a horrible explanation, but here's what it boils down to in code:

https://github.com/zenparsing/zen-observable/blob/sync-from-of/src/Observable.js#L355

**Comment by ljharb** [comment]
@zenparsing could `next` receive a second boolean argument, indicating "closed" or not?

**Comment by zenparsing** [comment]
@ljharb Well, the second argument would always be `true`, since the source observable wouldn't send data if it were closed.  You can solve the use case by providing a "subscription" argument to `next` though, and I experimented with that approach.  There are a couple of things that I didn't like about providing additional arguments:

- It changes the type relationship between the `SubscriptionObserver` ("SafeObserver", in Rx-speak) and a regular Observer, because the type signature of the next method is different.  A SubscriptionObserver would only take one argument for next whereas a regular Observer would now take two arguments.  That breaking of the subtype relationship worries me.
- It is sometimes convenient to be able to also query the "closed" status of a subscription object: https://github.com/zenparsing/zen-observable/blob/sync-from-of/src/Observable.js#L493
- In my opinion, it feels more ergonomic to query a "closed" property than rely on a second argument.

For comparison:

- Map with "closed" property: https://github.com/zenparsing/zen-observable/blob/next-subscription-arg/src/Observable.js#L350
- Map with subscription argument to next: https://github.com/zenparsing/zen-observable/blob/sync-from-of/src/Observable.js#L353

**Comment by benjamingr** [comment]
I thought we were looking into adding the subscription as an argument?

**Comment by blesh** [comment]
@zenparsing ... I think you're links are off in your previous comment. PROTIP: If you hit <kbd>Y</kbd> on any code page in Github, it'll update the URL to point only at the current revision. Then you can link to a line and have some confidence it won't change.

**Comment by blesh** [comment]
RxJS 5 uses this approach, and I like it. It helps in some areas like when you're creating a range:

```
function range(start, length) {
  return new Observable(observer => {
    cons stop = start + length;
    let i = start;
    while (!observer.isUnsubscribed && i < stop) {
      observer.next(i++);
    }
    observer.complete();
  });
}
```

**Comment by blesh** [comment]
I had a thought about the name of this (both here and in RxJS) today: it's not really `isUnsubscribed`, because the act of unsubscription/teardown hasn't occurred yet when it's flipped, really it's `isStopped` or something.

**Comment by zenparsing** [comment]
Right. That's why I chose "closed". I think generally we leave off the "is" for boolean instance getters or properties (e.g. descriptor.enumerable instead of isEnumerable).

**Comment by zenparsing** [comment]
Added `closed` getter to Subscription and SubscriptionObserver.
