### ISSUE TITLE
`enqueueJob` is problematic

### ISSUE THREAD

**Issue by benjamingr** [zenparsing/es-observable#92]
Hey, the scheduling we have here is pretty naive in the polyfill. Also, it uses microtask and macrotask semantics sometimes depending on different aspects - it also doesn't work in some cases (recent iOS using MutationObservers and inactive tabs have issues). 

If this gets removed then great (as we're discussing removing `of` and `from` in other threads). If it doesn't I think it's better to use `Promise.resolve().then(task)`  instead.

**Comment by zloirock** [comment]
`EnqueueJob` for `Promise` and `Observable` should use different microtask queues. In browsers, we have not any correct alternative for `MutationObserver`.

**Comment by benjamingr** [comment]
@zloirock 

> EnqueueJob for Promise and Observable should use different microtask queues

Why? 

For what it's worth from what it currently looks like, observables will emit synchronously and concurrency is left to the producer.

**Comment by zloirock** [comment]
@benjamingr I updated my comment. `EnqueueJob` first argument is a queue name and for `Promise` it's `"PromiseJobs"`. In the polyfill specified ["Non-Promise Job Queueing"](https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L1), but in the spec text also used `"PromiseJobs"` queue.

**Comment by benjamingr** [comment]
Honestly I think that the way we're heading the "polyfill" for enqueueing jobs will be removed anyway - but if it won't we should use reasonable scheduling.

**Comment by zenparsing** [comment]
"enqueJob" is removed.
