### ISSUE TITLE
How is `SubscriptionObserver` actually used?

### ISSUE THREAD

**Issue by eddieajau** [zenparsing/es-observable#94]
I hope this is ok to ask, but I'm trying to work through the example implementation and reconcile it with the specification.

The `SubscriberFunction` is supposed to be passed a `SubscriptionObserver `, but the implementation passes the actual [observer](https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L134). How will the `SubscriptionObserver` actually work in practice?

Thanks in advance.

**Comment by zenparsing** [comment]
You can see here https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L91 that the passed observer is converted to a SubscriptionObserver before being passed into the subscriber function.
