### ISSUE TITLE
Reactive-Streams-like API instead?

### ISSUE THREAD

**Issue by akarnokd** [zenparsing/es-observable#95]
Have you tought about defining the Observable like the Reactive-Streams specification (minus backpressure)?

The problem with the classical Rx.NET style Observable is that it forces asynchronous sources, otherwise the unsubscription doesn't work. In Reactive-Streams, the Observable injects the cancellation callback into the observer which can now cancel the sequence from the same thread.

The current RxJS has this original style and a simple `range` operation has quite an overhead.

So the spec would be:

```java
interface Observable {
    subscribe(s: Subscriber) : void;
}

interface Subscriber {
   onSubscribe(s: Subscription) : void;
   onNext(t) : void;
   onError(t) : void;
   onComplete() : void;
}

interface Subscription {
    unsubscribe() : void;
}
```

**Comment by benjamingr** [comment]
> Have you tought about defining the Observable like the Reactive-Streams specification (minus backpressure)?

Yes, many times over and in different variations, there are a lot of issues about this (passing the subscription as an argument, deferring the subscription and so on).

**Comment by akarnokd** [comment]
I generally wouldn't mind but since this is going to be the standard (right?), you may engrave a an older approach into EcmaScript. Certainly, library developers have more things to consider, but it's still easier to develop because of the guaranteed single-threadedness. Plus, there are now a couple of libraries out there who managed to work out the subscription management and deferring aspects.

**Comment by benjamingr** [comment]
You're definitely correct in that it's important to get the API right. 

The API is co-developed with RxJS 5 which is a grounds up rewrite of RxJS into the newer API and in coordination with various stake-holders. I'm hardly the authority on anything related to Rx, but you're welcome to stick around and follow things.

Some discussion related to synchronous subscriptions in:

 - https://github.com/zenparsing/es-observable/issues/81
 - https://github.com/zenparsing/es-observable/issues/83 

and others.

**Comment by zenparsing** [comment]
We've added an optional "start" method to the observer https://github.com/zenparsing/es-observable/blob/7162ae69da1a1e1ca3e2fa6d0dbde589674b7051/src/Observable.js#L81 which maps to "onSubscribe".

**Comment by akarnokd** [comment]
FYI, we started doing a proper Reactive-Streams based implementation on our own: https://github.com/reactor/reactor-core-js

Btw, the biggest hurdle with the classic Rx approach is the inability to cancel a sequence synchronously. Since JavaScript is practically a single-threaded, trampolined synchronous execution environment, that means a simple `range()` has to go ˙setTimeout` for each of its values, yielding 3-10x larger overhead.
